### ISSUE TITLE
[Feature] Allow Virtual, Page and Filter to run against a API Request

### ISSUE THREAD

**Issue by giusepe** [reactivemarbles/DynamicData#123]
Hello, 

If I understand correctly, currently all operators on DD will filter, sort, etc act in memory data.

So if I have a paged result with 25 items per page, with 3 pages in a total of 75 items and I'm on the first page, when I run `Filter(x => x.Name = "abc")` only the first 25 items will be considered and evaluated. 
I understand that what is expected for DD to do, but I would like to have an option to link the `Filter` method to a method inside my domain and run the search on the server.

Not sure how to do so, but I was thinking of something in the lines of when setting my `ICache movieCache` on the domain I could say something like 
`movieCache.FilterRemoteMethod(filterFunc => GetMovieFromApi(filterFunc))` 
And if I had it set, every time I would call `Filter` on the VM it would automatically redirect the Func into the method, that in this case would make the API call.

**Comment by robsonj** [comment]
I think this is already covered by the following extension...

```csharp
        /// <summary>
        /// Creates a filtered stream which can be dynamically filtered
        /// </summary>
        /// <typeparam name="TObject">The type of the object.</typeparam>
        /// <typeparam name="TKey">The type of the key.</typeparam>
        /// <param name="source">The source.</param>
        /// <param name="reapplyFilter">Observable to re-evaluate whether the filter still matches items. Use when filtering on mutable values</param>
        /// <param name="predicateChanged">Observable to change the underlying predicate.</param>
        /// <returns></returns>
        public static IObservable<IChangeSet<TObject, TKey>> Filter<TObject, TKey>([NotNull] this IObservable<IChangeSet<TObject, TKey>> source,
            [NotNull] IObservable<Func<TObject, bool>> predicateChanged,
            [NotNull] IObservable<Unit> reapplyFilter)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (predicateChanged == null) throw new ArgumentNullException(nameof(predicateChanged));
            if (reapplyFilter == null) throw new ArgumentNullException(nameof(reapplyFilter));
            return new DynamicFilter<TObject, TKey>(source, predicateChanged, reapplyFilter).Run();
        }
```

**Comment by giusepe** [comment]
Hey @robsonj, thanks for your reply :)

I'll look further into this and try a little, but it seems that doesn't it covers what I'm looking for.
By any chance, you don't have a sample on how this would work?

**Comment by RolandPheasant** [comment]
@robsonj the filter operator only allows filtering of data on in-memory data and makes no provisions for fetching data from an external source.

@giusepe for some time I have been thinking about how the visualise and page operators could be improved to enable true loading of data on-demand. I would like to take this one on but I know for sure there will be a many complexities stemming from subtle differences between the way different applications manage the loading of data. 

 There are several kinds of virtualisation with various ways of managing data including

 - Continuous scrolling when more data is loaded as a user scrolls downwards - akin to Facebook. Also a great example can be found courtesy of @modplug https://github.com/modplug/VirtualizedData 
 - Paging where a user clicks "load more" or "next page" - this is classic old school paging
 - Virtualisation where data is loaded / unloaded such that the only in-memory data is what is displayed on the screen - an example of this is TailBlazer (my app) 

I am sure there are other methodologies so feel free to let me know of anything which has been missed out or better still add a detailed scenario which you would like to see supported.

I think an good prototype to start with will be to abstract the example by @modplug and see whether the idea can be generalised

**Comment by hungnd1475** [comment]
Hi @RolandPheasant, regarding data virtualisation I would like to point out a scenario that is officially supported in UWP (https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/listview-and-gridview-data-optimization). Microsoft also provides a reference implementation to support random access data virtualisation here https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/XamlDataVirtualization . I'm wondering whether this idea can be applied to dynamicdata.

**Comment by RolandPheasant** [comment]
@hungnd1475  In theory there could add such specialisations. However I have been reluctant to put platform specific implementations in the lib itself as it would inject a huge amount of complexity when maintaining this lib.  That said, if someone could get give an example of a base implementation outside the lib then a conversation could be had about whether to onboard it, or create a new Nuget pacakage
