### ISSUE TITLE
SubscribeMany unsubscribes automatically on ChangeSet observable completion

### ISSUE THREAD

**Issue by ltrzesniewski** [reactivemarbles/DynamicData#144]
I'm not sure if this is a bug or if it's by design, but my code definitely ended up behaving in a way I didn't expect because of that.

When a change set sequence completes, the sequence may still represent a non-empty collection at that point. The completion of a change set only means the collection won't change any further.

Yet `SubscribeMany`, and other operators which use it such as `MergeMany` and `WhenPropertyChanged` seem to assume the collection is emptied by the completion of the change set sequence.

Consider the following:

```C#
internal static class Program
{
    public static void Main()
    {
        var foo = new Foo();

        var subscription = new[] { foo }
                           .ToObservable()
                           .ToObservableChangeSet()
                           //.Concat(Observable.Never<IChangeSet<Foo>>())
                           .Do(
                               i => Console.WriteLine($"ChangeSet: {i}"),
                               () => Console.WriteLine("ChangeSet completed")
                           )
                           .WhenPropertyChanged(i => i.Bar)
                           .Subscribe(
                               i => Console.WriteLine($"Value: {i.Value}"),
                               () => Console.WriteLine("Completed")
                           );

        foo.Bar = 42;

        subscription.Dispose();
    }
}

internal class Foo : INotifyPropertyChanged
{
    private PropertyChangedEventHandler _propertyChanged;
    private int _bar;

    public int Bar
    {
        get => _bar;
        set
        {
            _bar = value;
            NotifyPropertyChanged();
        }
    }

    public event PropertyChangedEventHandler PropertyChanged
    {
        add
        {
            _propertyChanged += value;
            Console.WriteLine("Added handler");
        }
        remove
        {
            _propertyChanged += value;
            Console.WriteLine("Removed handler");
        }
    }

    private void NotifyPropertyChanged([CallerMemberName] string propertyName = null)
    {
        Console.WriteLine($"Notifying change: {propertyName}");
        _propertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

This uses a sequence consisting of a single change set which adds a `Foo` instance and then completes. 
**Logically, the instance is still in the collection produced by the change set at that point.**

This produces the following result:

> ChangeSet: ChangeSet<Foo>. Count=1
Value: 0
Added handler
ChangeSet completed
Removed handler
Notifying change: Bar

Here's the output I expected:

> ChangeSet: ChangeSet<Foo>. Count=1
Value: 0
Added handler
ChangeSet completed
Notifying change: Bar
Value: 42
Removed handler

Current workaround: if you uncomment the `.Concat(Observable.Never<IChangeSet<Foo>>())` line, the output changes to:

> ChangeSet: ChangeSet<Foo>. Count=1
Value: 0
Added handler
Notifying change: Bar
Value: 42
Removed handler

**Comment by RolandPheasant** [comment]
This is intended behaviour.  Dynamic Data is following Rx conventions

The convention in this case is when an observerable completes  all subscribers also complete.

The work around of ``.Concat(Observable.Never<IChangeSet<Foo>>())``` is a perfectly legitimate means of keeping the observable alive.

**Comment by ltrzesniewski** [comment]
Hmm... Sorry but I'm not really convinced here. 😉 

Let's write a very similar example to the above, but using pure Rx:

```C#
internal class Program
{
    public static void Main()
    {
        var foo = new Subject<int>();

        var subscription = new[] { 0 }
            .ToObservable()
            .Do(
                i => Console.WriteLine($"Item: {i}"),
                () => Console.WriteLine("Item sequence completed")
            )
            .SelectMany(i => foo)
            .Subscribe(
                i => Console.WriteLine($"Foo: {i}"),
                () => Console.WriteLine("Foo Completed")
            );

        foo.OnNext(42);

        subscription.Dispose();
    }
}
```

The result is:

> Item: 0
Item sequence completed
Foo: 42

So you can see the `SelectMany` operator didn't just stop its sequence when the upstream sequence completed. I expected `WhenPropertyChanged` to be very similar to `SelectMany` in this regard.
