### ISSUE TITLE
TransformMany does not work with IObservableList

### ISSUE THREAD

**Issue by ronaldvdv** [reactivemarbles/DynamicData#158]
I'm creating a Parent class that exposes a "Children" property of type `IObservableList<TChild>`. Then when I have an `IObservable<Parent>`, I would like to create another observable that represents the relation to the children such that a change of the Parent or a change in the collection of children are propagated.

For this I would like to use `parentObservable.ToObservableChangeSet().TransformMany(parent => parent.Children)` but as far as I can see, the TransformMany does not contain an overload that recognizes a `Func<TSource, IObservableList<TDestination>>`. Therefore the `Func<TSource, IEnumerable<TDestination>>` is used instead which does not propagate changes in the child collection.

Sample code:

```
class Parent {
  private SourceList<Child> _children;
  public IObservableList<Child> Children => _children.AsObservableList();
}

class Child { }

IObservable<Parent> parent; // Set elsewhere
var subscription = parent.ToObservableChangeSet().TransformMany(p => p.Children).Bind(out list).Subscribe();
```

**Comment by RolandPheasant** [comment]
The desired result can be achieved  using the logical collection operations

```.Transform(p => p.Children).Or();```

See [Composite Collections](https://github.com/RolandPheasant/DynamicData/wiki/Composite-Collections)

**Comment by ronaldvdv** [comment]
Thanks for following up on this! However, I struggle to get your solution to work:

- ToObservableChangeSet gives a result of type IObservable<IChangeSet<Parent>> 
- Transform then gives a result of type IObservable<IChangeSet<IObservableList<Child>>>
- Or then gives me the same result type

Also looking at the source code (List/ObservableListEx.cs), I cannot find overloads for the Or operator that accept IObservable<IChangeSet<IObservableList<Child>>> and return IObservable<IChangeSet<Child>> ; they either combine multiple sources, or expect an observable list as the outer type.

Did I misunderstand your solution or would I need a different approach to get this to work?

Also, looking at the source code for TransformMany, it seems odd that there is no overload that accepts a manyselector of type Func<TSource, IObservableList<TDestination>>  ... wouldn't that be the most straight-forward approach? Happy to help out with a PR if you agree this is the better approach instead.

**Comment by RolandPheasant** [comment]
Change 

```_children.AsObservableList```

to

```_children.Connect()```

**Comment by RolandPheasant** [comment]
Also a PR for the other overload would be welcome

**Comment by ronaldvdv** [comment]
@RolandPheasant  How about just adding a constructor to `TransformMany<TSource, TDestination>` class that takes a `Func<TSource, IObservableList<TDestination>>` as follows:

```
public TransformMany(IObservable<IChangeSet<TSource>> source,
    Func<TSource, IObservableList<TDestination>> manyselector,
    IEqualityComparer<TDestination> equalityComparer = null)
    : this(source, s => manyselector(s).Items, equalityComparer, t => Observable.Defer(() => {
        var subsequentChanges = manyselector(t).Connect();

        if (manyselector(t).Count > 0)
            return subsequentChanges;

        return Observable.Return(ChangeSet<TDestination>.Empty)
            .Concat(subsequentChanges);
    }))
{
}
```

**Comment by RolandPheasant** [comment]
The overload is fine and I would welcome a PR.  Conceptually it should all work but will require a lot of work to make it optimal. I suggest for iteration one we make it work and worry about performance as a secondary concern
