### ISSUE TITLE
AsAbservableList with dynamic filter on SourceCache

### ISSUE THREAD

**Issue by WernerGe** [reactivemarbles/DynamicData#171]
Testing and wanting to use  the issue #164 "Dynamic Filter with SourceList" for SourceCache and extending both with a derived AsObservableList respectively AsObservableCache I found out that the AsObservableCache gets NOT updated on inserting and removing items from the SourceCache (with ObservableList all works fine).

I was taking the source from #164 from Liklainy, changed it for ObservableCache and added the following:
```
      var obsCache = sourceCache.Connect()
		.Filter(dynamicFilter)
		.AsObservableCache();

	obsCache.CountChanged.Subscribe(x => $"AsObservableCache: Count = {x}".Dump());
```
The above code does not react to list changes (the same code for ObservableList works fine!)

**Output for ObservableCache (NO UPDATES)**
```
AsObservableCache: Count = 0
Add item to cache
Add items to cache
Items in collection: 5

Show User 0
Changes: 5
Items: 10,0,1,2,3

Remove items from list
Remove items: 0,1
Remove innerList count: 3
Changes: 2
Items: 10,2,3

Show User 1
Changes: 3
Items:
```

**Output of Observable List (WORKS FINE)**
```
AsObservableList: Count = 0
Add items to list
Items in collection: 4

Show User 0
Changes: 4
Items: 0,1,2,3
AsObservableList: Count = 4

Remove items from list
Remove: 0,1
Remove count: 2
Changes: 2
Items: 2,3
AsObservableList: Count = 2

Show User 1
Changes: 2
Items: 
AsObservableList: Count = 0`
```
Attached are both sources for ObservableList and ObservableCache for execution in LinqPad

[DynamicFilterAsObservable.zip](https://github.com/RolandPheasant/DynamicData/files/2535446/DynamicFilterAsObservable.zip)

**Comment by WernerGe** [comment]
Looks like the observable cache is updated correctly and contains the proper items BUT the subscription to CountChanged does not fire!

**Comment by WernerGe** [comment]
Adding a subscription to the derived observable cache the subscription to CountChanged works, too ?!?
```
	var obsCache = list.Connect()
		.Filter(dynamicFilter)
		.AsObservableCache();
		
	obsCache.Connect().Subscribe(x => Console.WriteLine("DummySubscription"));
	obsCache.CountChanged.Subscribe(x => Console.WriteLine($"AsObservableCache count = {x}"));
```
Removing the DummySubscription line subscription to CountChanged does NOT fire.

**Comment by RolandPheasant** [comment]
That looks like a bug to me. I'll take a look

**Comment by RolandPheasant** [comment]
Can you check this again. I think it works now.
