### ISSUE TITLE
AutoRefreshOnObservable followed by Transform does not trigger a refresh

### ISSUE THREAD

**Issue by samirem** [reactivemarbles/DynamicData#180]
The `AutoRefreshOnObservable` does not trigger a refresh in the following snippet
```
MyObservableCache.Connect()
    .AutoRefreshOnObservable(_ => refreshObservable)
    .Transform(x =>...)
    .AsObservableCache();
```
I've tried setting breakpoints and it hits the one in the `refreshObservable` but not the `Transform`.

Tried with version 6.6.1.2516 of the library.

**Comment by grokys** [comment]
I too am having this problem. #185 was closed saying:

>  You can use the all items observable as it is but instead of using the `AutoRefresh` operator, call the `Refresh` method on the source cache

However I am using a `SourceList` and that doesn't have a `Refresh` method. What should I do in this case?

**Comment by Claye-L** [comment]
The problem mentioned in the first post is easily solved by doing ```.Transform(x => someItem, true)``` which enables the "transformOnRefresh".

**Comment by grokys** [comment]
Ah yes, `transformOnRefresh` helps for the `SourceList` case too, although I assume it's still causing a subscription for each item which isn't ideal performance-wise.
