### ISSUE TITLE
Calling Clear() on an SourceList<T> throws "Index was out of range." exception

### ISSUE THREAD

**Issue by andrejpanjan** [reactivemarbles/DynamicData#191]
Sometimes when calling `Clear()` on an `SourceList<T>` an exception "Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index" is thrown. There are no parallel task that could change the list while it is being cleared.
Why would the `Clear()` method throw that exception anyway?

Currently I use a workaround with `RemoveAt(int index)` to clear the list.

**Comment by RolandPheasant** [comment]
Clearing this is a bug.

Would it be possible for you to create a breaking unit test, replicating the issue?

**Comment by andrejpanjan** [comment]
I'm not able to create a breaking unit test. So far, I get the warning only in my app. It always throws the warning after the same sequence of calls. However, it doesn't throw it on the same `SourceList` (with the same items) if I use another sequence of calls. But those sequences of calls don't do anything with the `SourceList`, except connecting to the read only `ObservableList` which exposes the `SourceList`.

I can provide anything that would help in solving the issue if you let me know what would help you.
