### ISSUE TITLE
Support for IItemsRangeInfo

### ISSUE THREAD

**Issue by wldevries** [reactivemarbles/DynamicData#200]
UWP has some great functionality to improve performance on containers with huge amounts of elements. Specifically it allows dynamically caching and pruning items that are presented. It would be great to have an UWP specific implementation of `ReadOnlyObservableCollection` that supports the functionality.

https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/listview-and-gridview-data-optimization
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Data.IItemsRangeInfo

**Comment by limefrogyank** [comment]
You could probably subclass ObservableCollectionExtended and add the `IItemsRangeInfo` interface yourself.  I'm currently doing that with `ISupportIncrementalLoading`

**Comment by wldevries** [comment]
How would you go about that? What I would like to achieve is to delay the transformation from model to viewmodel and pool viewmodels for reuse. It seems I'm already too late when implementing the `ObservableCollectionExtended` because it has no say over which items are actualized.
