### ISSUE TITLE
SourceList RemoveAt using IComparer to remove the wrong item

### ISSUE THREAD

**Issue by kernshen** [reactivemarbles/DynamicData#201]
In the following example, source.RemoveAt(2) will trigger TupleComparer to remove (2, "A"), instead of (3, "A"). This shouldn't be the case right?

Using source.RemoveRange(2, 1) works correctly to remove (3, "A").

    public partial class MainPage : ContentPage
    {
        protected SourceList<Tuple<int, string>> source;
        public ReadOnlyObservableCollection<Tuple<int, string>> List { get; }

        public MainPage()
        {
            InitializeComponent();
                        
            source = new SourceList<Tuple<int, string>>();

            source.Connect()
                .Sort(new TupleComparer(), SortOptions.UseBinarySearch)
                .ObserveOn(RxApp.MainThreadScheduler)
                .Bind(out var tuples)
                .DisposeMany()
                .Subscribe();

            List = tuples;

            source.AddRange(new Tuple<int, string>[] { new Tuple<int, string>(1, "A"), new Tuple<int, string>(2, "A"), new Tuple<int, string>(3, "A") });

            lvList.ItemsSource = List;
        }
    }

    public class TupleComparer: IComparer<Tuple<int, string>>
    {
        public int Compare(Tuple<int, string> a, Tuple<int, string> b)
        {
            return string.Compare(a.Item2, b.Item2);
        }
    }

**Comment by kernshen** [comment]
I realised that the correct item is removed in "source" but not "List".

And it seems to be due to SortOptions.UseBinarySearch.  Changing to SortOptions.None will have the correct item removed from both "source" and "List".

**Comment by lippling** [comment]
I think I have a similar problem:

```
...
sourceList.Edit(updater => updater.RemoveAt(...));
...
```
Does not remove items in `_list`:
```
...
.Transform(i => new Wrapper(i))
.Bind(out _list);
```

works as expected:
```
...
.Bind(out _list);
```

**Comment by RolandPheasant** [comment]
Binary search will only work when Items are truly unique and have an immutable hash code.
