### ISSUE TITLE
Howto use AutoRefresh or WhenAnyPropertyChanged and define notification on all except some properties.

### ISSUE THREAD

**Issue by sa-he** [reactivemarbles/DynamicData#214]
Right now the best I found is listing all properties I want to monitor. See code snippet below - however the list of properties in my scenario is growing much longer.

Most importantly this approach is not refactoring safe. Every time someone adds a new property (which happens a lot at this early state of our project), we need to remember to also add it as new parameter of WhenAnyPropertyChanged(..)

Any ideas to solve this better?

```C#
.WhenAnyPropertyChanged(nameof(MyClass.X), nameof(MyClass.Y))

**Comment by alexmartinezm** [comment]
Hi there!

You could decorate your properties with some custom attribute and then retrieve all the properties with that attribute and pass them to the `. WhenAnyPropertyChanged`.

**Comment by SchwabenProgger** [comment]
Thank you for your extensive answer. It is for sure a better approach than writing all by hand.

I was however hoping there was a native method overload that would do exactly what I need. Something like:

```C#
.WhenAnyPropertyChangedExcept(nameof(MyClass.IgnoreMe1), nameof(MyClass.IgnoreMe2))
// or
.AutoRefreshAllExcept(m => m.IgnoreMe1, m => m.IgnoreMe2)

**Comment by SchwabenProgger** [comment]
Thank you for your extensive answer. It is for sure a better approach than writing all by hand.

I was however hoping there was a native method overload that would do exactly what I need. Something like:

```C#
.WhenAnyPropertyChangedExcept(nameof(MyClass.IgnoreMe1), nameof(MyClass.IgnoreMe2))
// or
.AutoRefreshAllExcept(m => m.IgnoreMe1, m => m.IgnoreMe2)
