### ISSUE TITLE
Changing SortExpressionComparer<T> on SourceCache works but incorrect output

### ISSUE THREAD

**Issue by toshihikotani** [reactivemarbles/DynamicData#217]
Hi Sir, I've been testing out to do some method that will change the SortExpressionComparer<T> on SourceCache property that I created by following one of your snippets (https://github.com/RolandPheasant/DynamicData.Snippets)

The changing functionality works but the sorting output is not correct. 

Thanks. :)

**Comment by oysteinkrog** [comment]
Please create a small unit test that shows the problem :)

**Comment by toshitani23** [comment]
Hi Sir, I'll send the zipped file via Google Drive. For the reason that the file is bigger than 10MB.

Thank you very much. :)
Let me know if you received it later. :)

**Comment by toshitani23** [comment]
[SortingTestApp.zip](https://github.com/RolandPheasant/DynamicData/files/3028338/SortingTestApp.zip)

I just fixed to compressed the files....Here's my sample unit that you requested. Thank you very much. :)

**Comment by RolandPheasant** [comment]
I somehow managed to miss this example. I just looked at it and sadly I cannot load it owing to the required SDKs not being installed. If it's still an issue please re-open
