### ISSUE TITLE
Add System.Linq.Dynamic.Core support in Filter

### ISSUE THREAD

**Issue by Chris55** [reactivemarbles/DynamicData#221]
to be able to write something like
var myFilteredObservable = myPeopleObservable.Filter("Age > 50"); 

here the filter as a string can be the UI search string.

instead of:
var myFilteredObservable = myPeopleObservable.Filter(person => person.Age > 50);

**Comment by limefrogyank** [comment]
Wow, I didn't know this existed... this would be easier to serialize than an `Expression`

**Comment by RolandPheasant** [comment]
I have no plans for this.
