### ISSUE TITLE
And logical operator gives unexpected result

### ISSUE THREAD

**Issue by PaulWagener** [reactivemarbles/DynamicData#223]
Combining two lists with AND with partially overlapping results gives unexpected results. For example, I would expect the lists [1, 2, 3] and [3, 4, 5] to result in a list of [3] as it is the only overlapping number. But instead the output is [1, 2, 3]. The propagated changes are first adding 1,2,3 and then updating just 3.

Or maybe I'm misunderstanding this feature?

````C#
var list1 = new SourceCache<int, int>(i => i);
var list2 = new SourceCache<int, int>(i => i);

list1.AddOrUpdate(1);
list1.AddOrUpdate(2);
list1.AddOrUpdate(3);

list2.AddOrUpdate(3);
list2.AddOrUpdate(4);
list2.AddOrUpdate(5);

var and = list1.Connect().And(list2.Connect());

and.ToCollection().Subscribe((l) =>
{
    Console.WriteLine($"[{string.Join(", ", l)}]"); // Produces "[1, 2, 3]", expected "[3]"
});
````

**Comment by PaulWagener** [comment]
This commit shows a unit test and a possible solution to the problem:
https://github.com/PaulWagener/DynamicData/commit/c5af7dd69e6cc3bd516faaf066a6b04ff29a5981

**Comment by RolandPheasant** [comment]
This is indeed a bug and thanks for the suggested fix. I have also taken a look and found an alternative fix to yours. I will push one of these in soon

**Comment by RolandPheasant** [comment]
Closed - already fixd
