### ISSUE TITLE
Consider using IPartition and IListProvider

### ISSUE THREAD

**Issue by glennawatson** [reactivemarbles/DynamicData#224]
Linq added some awareness of bypass operations for standard operations to speed things up.

They achieve this with the IPartition and the IListProvider interfaces

https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/IPartition.cs
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/IIListProvider.cs

Eg if someone uses Linq Count() method, if there is a IListProvider, it'll use that Count() method instead of using the Enumerable.Count method.

Not sure where you want to use it but just making you aware of these optimisations.

**Comment by RolandPheasant** [comment]
I was not aware of this. Thanks for bring to my attention. I will consider where it can be used
