### ISSUE TITLE
Namespace collision with System.Reactive.Linq

### ISSUE THREAD

**Issue by wldevries** [reactivemarbles/DynamicData#255]
**Is your feature request related to a problem? Please describe.**

I was trying to create a `Count` observable from a `SourceCache` which did not provide any results. The problem was that I had the namespace `System.Reactive.Linq`, but not `DynamicData.Aggregation` which caused the wrong extension method to be picked.

**Describe the solution you'd like**

I added a `DynamicData.Aggregation` using statement.

**Describe alternatives you've considered**

-

**Describe suggestions on how to achieve the feature**

It would be nice to include a warning note about using the correct namespace in the aggregation section of the README.md.

**Additional context**

-

**Comment by glennawatson** [comment]
Happy for a PR to be made for addition to the readme documentation. It'd be a nice easy one to do.

**Comment by roceh** [comment]
new to reactiveui/dynamicdata, this one caught me out also doing canExecute checks. easy to miss if you have already imported System.Reactive.Linq as it compiles fine, but doesn't work.
