### ISSUE TITLE
[BUG] Incorrect behaviour for .DisposeWith() or .OnItemRemoved()

### ISSUE THREAD

**Issue by arrteamgun** [reactivemarbles/DynamicData#268]
**Describe the bug**

Found a bug when .DisposeWith() works incorrectly with SourceCache

If you use code below without comments it works incorrectly - it can't reach .OnItemRemoved()
With comments it works well.

```
medboxesRegistry.Items
                    .ToObservableChangeSet(/*device => device.Model.Id*/)
                    .Transform(medbox =>
                    {
                        return new MedboxMedicineLocationViewModel(medbox, logger);
                    })
                    .OnItemAdded(vm => vm.Activator.IsActive = true)
                    .OnItemRemoved(vm => vm.Activator.IsActive = false)
                    .ToSortedCollection(device => device.Medbox.Name)
                    .ToProperty(this, vm => vm.AvailableLocations, out availableLocations)
                    .DisposeWith(d);
```

**Steps To Reproduce**

1. Run this code with `/*device => device.Model.Id*/`
2. Run this code with `device => device.Model.Id`
3. It works differently for this approaches

**Expected behavior**

It works the same with or without comments.
Or it works correctly with .OnItemRemoved()

**Environment**

- OS:       iOS simulator
- Library Version: 6.12.0

**Comment by RolandPheasant** [comment]
What do you mean by "It works differently.."?

**Comment by RolandPheasant** [comment]
I see, what you mean is there is an inconsistency between source list and source cache. However we need to narrow this down is why. Would you mind creating a broken unit test to help me to diagnose the issue?

**Comment by arrteamgun** [comment]
[OnItemRemoved.zip](https://github.com/reactiveui/DynamicData/files/3549391/OnItemRemoved.zip)

**Comment by RolandPheasant** [comment]
Thanks for the reproduction.  The issue is that for the cache, OnItemRemoved is not applied when disposed whereas it is for the list.  The question now whether change the default behaviour of one of the other, or whether to add overloads stipulating whether the call back is required when  disposed

Btw, Sorry for the delay in answering but I have been on holidays.

**Comment by RolandPheasant** [comment]
Better late than never - fixed!

The cache did not formerly invoke OnBeingRemoved when the stream was disposed. Now it does.
