### ISSUE TITLE
How to aggregate a reactive tree while maintaining the tree structure.

### ISSUE THREAD

**Issue by Claye-L** [reactivemarbles/DynamicData#270]
**Is your feature request related to a problem? Please describe.**

I have a domain that is represented by a tree structure.  I have a model 
```cs
class Department 
{
public int Id{get;}
public decimal Cost {get;}
public int? ParentDepartment {get;}
public Department(int id, decimal cost, int? parentId = null) 
{
    Id = id;
    Cost = cost;
    ParentDepartment = parentId;
}
}
```
Obviously i tired to model it using a ReactiveTree, however i can't figure out how to do some kind of aggregate tree. What i mean is, Keep the tree structure, but every node is the added cost of the department and all its children department, while keeping the good features of dynamic data: reacting to changes in the most efficient way. I made a quick drawing of my data and what i'd want to achieve
![AggregateTreeSchema](https://user-images.githubusercontent.com/43422061/64027564-3c825d00-cb41-11e9-9566-d6326007cd1b.png)
**Describe what solution you'd like"
What's important to me is the ability at any time to know the aggregate at any level, not just at the top level.

**Describe alternatives you've considered**

I've considered creating proxy items at every stage of the tree, that expose a Cost property and connect to their children and compute their sum. However i'm wary of going that way because changes to an entity trigger a whole new unsub/resub to the children . Also of concern is how to properly implement summing the children so i'd only have to sum on 1 level of children (eg the boss only has to look at dep a and dep b to know everything about the deps below).

**Additional context**

Obvisouly I simplified my domain for my example, but in my domain, computing the total for one department is more complex than just looking at one property, so that's the motivation behind my request for not resubscribing children multiple times. A lot of my business logic is already implemented using Rx so i'd like to have a unified way of doing things.

Hopefully that was clear and you'll be able to help me. Tell me if this isn't the right place to ask this kind of open ended question.

**Comment by RolandPheasant** [comment]
I have to say I am not at all sure and I also have to admit that I scream whenever I even consider anything to do with the TransformTree operator as it melts my mind every time.

If you still need to discuss this please join the slack channel and ping me there,
