### ISSUE TITLE
Shouldn't Count() provide '0' for an empty source cache?

### ISSUE THREAD

**Issue by StefanDoubleU** [reactivemarbles/DynamicData#29]
I came across the need of an observable for the number of elements in an source cache.

```
var sourceCache = new SourceCache<string, int>(s => s.GetHashCode());

sourceCache.Connect()
            .Count()
            .Dump();

sourceCache.AddOrUpdate("test");
```

Result is:

```
IObservable<Int32>
1
```

From my point of view, the expected behavior should be:

```
IObservable<Int32>
0
1
```

**Comment by RolandPheasant** [comment]
Yes it should and something I have been meaning to sort out. Now that you  have raised the issue I will get on the case.

**Comment by RolandPheasant** [comment]
To work around the problem  use start with(0) after the count

**Comment by StefanDoubleU** [comment]
That's what I did, but wanted to inform you. Thanks
