### ISSUE TITLE
[BUG] ChangeSet from Connect() of SourceList in wrong order when adding new items in an OnItemAdded() handler

### ISSUE THREAD

**Issue by PeterH-euris** [reactivemarbles/DynamicData#301]
**Describe the bug**
When you use the OnItemAdded() method to react to ChangeSets of a SourceList and add new items to a SourceList, the order of the generated "Add" ChangeSets might be wrong depending on the order of using Subscribe() or OnItemAdded() on the ChangeSet observable returned by Connect(). This will result in a follow up exception in any classes which consume the ChangeSets (like binding onto a ReadOnlyObservableCollection).

**Steps To Reproduce**

        [TestMethod]
        public void DynamicDataReaddTest()
        {
            SourceList<int> source = new SourceList<int>();
            
            IList<int> indices = new List<int>();

            /*  Block A begin */
            source.Connect().OnItemAdded(it =>
                {
                    if (it == 5)
                    {
                        source.Add(10);
                    }
                })
                .Subscribe(_ => { }, ex => Assert.Fail());
            /*  Block A end */

            /*  Block B begin */
            source.Connect().Subscribe(it =>
            {
                System.Diagnostics.Debug.WriteLine(it);
                foreach (Change<int> change in it)
                {
                    Debug.WriteLine($"## Change: {change}");
                    ItemChange<int> item = change.Item;
                    Debug.WriteLine($"## Item: {item}");
                    Debug.WriteLine($"## Item.CurrentIndex: {item.CurrentIndex}, Item.Current: {item.Current}");
                    indices.Add(item.CurrentIndex);
                }
            }, ex => Assert.Fail());
            /*  Block B end */
            
            source.Add(5);

            CollectionAssert.AreEqual(new List<int> {0, 1}, indices.ToCollection());
        }

When you run this unit test it will fail and will generate the following debug output:
```
ChangeSet<Int32>. Count=1
## Change: Add. Current: 10, Previous: <None>
## Item: Current: 10, Previous: <None>
## Item.CurrentIndex: 1, Item.Current: 10
ChangeSet<Int32>. Count=1
## Change: Add. Current: 5, Previous: <None>
## Item: Current: 5, Previous: <None>
## Item.CurrentIndex: 0, Item.Current: 5
```

As you see, the "Add" ChangeSet for the second number added comes first (CurrentIndex=1), then the "Add" ChangeSet for the first number added comes second (CurrentIndex=0). This results in an ArgumentOutOfRangeException in the ReadOnlyObservableCollection because the CurrentIndex=1 is not valid (yet).

If you swap the blocks "A" and "B" to change the order when a subscription is build you will get the correct order:

        [TestMethod]
        public void DynamicDataReaddTest()
        {
            SourceList<int> source = new SourceList<int>();
            
            IList<int> indices = new List<int>();

            /*  Block B begin */
            source.Connect().Subscribe(it =>
            {
                System.Diagnostics.Debug.WriteLine(it);
                foreach (Change<int> change in it)
                {
                    Debug.WriteLine($"## Change: {change}");
                    ItemChange<int> item = change.Item;
                    Debug.WriteLine($"## Item: {item}");
                    Debug.WriteLine($"## Item.CurrentIndex: {item.CurrentIndex}, Item.Current: {item.Current}");
                    indices.Add(item.CurrentIndex);
                }
            }, ex => Assert.Fail());
            /*  Block B end */
            
            /*  Block A begin */
            source.Connect().OnItemAdded(it =>
                {
                    if (it == 5)
                    {
                        source.Add(10);
                    }
                })
                .Subscribe(_ => { }, ex => Assert.Fail());
            /*  Block A end */
            
            source.Add(5);

            CollectionAssert.AreEqual(new List<int> {0, 1}, indices.ToCollection());
        }

This will pass the unit test and create the following debug output:

```
ChangeSet<Int32>. Count=1
## Change: Add. Current: 5, Previous: <None>
## Item: Current: 5, Previous: <None>
## Item.CurrentIndex: 0, Item.Current: 5
ChangeSet<Int32>. Count=1
## Change: Add. Current: 10, Previous: <None>
## Item: Current: 10, Previous: <None>
## Item.CurrentIndex: 1, Item.Current: 10
```

**Expected behavior**

The order of the ChangeSet items/events should be the same regardless of the order of subscriptions build on the observable returned by Connect().

**Environment**
- Version:  DynamicData 6.13.20

**Comment by RolandPheasant** [comment]
The reason for them not being in order is `OnItemsAdded` only reports changes in the order which changes took place, and not the final list order.  The intentions of this operator has never been for it to be used to recreate an observable list as there are many other ways of doing that.

I am not sure it is desirable to to add the extra  weight of maintaining order for an operator which is meany to be a light weight side effect.

**Comment by PeterH-euris** [comment]
I'm a little bit confused why the `Bind()` operator shouldn't be used to recreate an observable list. Isn't that the only purpose of the `Bind()` operator? The problem is that the `ReadOnlyObservableCollection` class can't handle the received `IChangeSet<>` objects being out of order as seen in this unit test:

```csharp
        [TestMethod]
        public void DynamicDataReaddTest()
        {
            SourceList<int> source = new SourceList<int>();
        
            /*  Block A begin */
            source.Connect().OnItemAdded(it =>
                {
                    if (it == 5)
                    {
                        source.Add(10);
                    }
                })
                .Subscribe(_ => { }, ex => Assert.Fail(ex.ToString()));
            /*  Block A end */
            
            /*  Block B begin */
            source.Connect()
                .Bind(out ReadOnlyObservableCollection<int> _)
                .Subscribe(_ => { }, ex => Assert.Fail(ex.ToString()));
            /*  Block B end */

            source.Add(5);
        }
```

This will fail with an `ArgumentOutOfRangeException` inside the `ReadOnlyObservableCollection`:

```
System.ArgumentOutOfRangeException: <<localized error message about index not in limits>>
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   bei DynamicData.ListEx.Clone[T](IList`1 source, Change`1 item, IEqualityComparer`1 equalityComparer) in d:\a\1\s\src\DynamicData\List\ListEx.cs:Zeile 86.
   bei DynamicData.ListEx.Clone[T](IList`1 source, IChangeSet`1 changes, IEqualityComparer`1 equalityComparer) in d:\a\1\s\src\DynamicData\List\ListEx.cs:Zeile 78.
   bei DynamicData.Binding.ObservableCollectionAdaptor`1.Adapt(IChangeSet`1 changes) in d:\a\1\s\src\DynamicData\Binding\ObservableCollectionAdaptor.cs:Zeile 48.
   bei DynamicData.ObservableListEx.<>c__DisplayClass21_0`1.<Adapt>b__1(IChangeSet`1 changes) in d:\a\1\s\src\DynamicData\List\ObservableListEx.cs:Zeile 593.
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:Zeile 39.
   bei Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   bei Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message)
```
