### ISSUE TITLE
[BUG] ObservableCache.Connect() omits changes if subscribed while cache is being updated

### ISSUE THREAD

**Issue by christopherpaul** [reactivemarbles/DynamicData#319]
Hi there! I noticed the following odd behaviour, which I think is a bug in `ObservableCache`.

**Describe the bug**
If I subscribe to the observable returned by `ObservableCache.Connect()` as items are being added to the cache on a separate thread, these additions are not reliably reflected in the changes received on the subscription.

**Steps To Reproduce**
The following code reproduces the issue fairly reliably on my PC.
```c#
            var source = Enumerable.Range(1, 10000)
                .ToObservable()
                .SubscribeOn(NewThreadScheduler.Default)
                //.Delay(TimeSpan.FromSeconds(1))
                .Publish();

            var cache = source
                .ToObservableChangeSet(x => x)
                .AsObservableCache();

            source.Connect();
            //await source.LastAsync();
            var allChanges = await cache.Connect().Flatten().Select(chg => chg.Current).ToList();

            Assert.That(allChanges, Is.EquivalentTo(Enumerable.Range(1, 10000)));
```

If I wait until the source has fully populated the cache (by uncommenting the `await` above), or if I delay populating the cache until after subscribing (by uncommenting the `Delay` above) then the result is as expected, which suggests this is a concurrent subscribe/update issue.

**Expected behavior**
`allChanges` should contain all 10000 items produced by `source`.

**Screenshots**

n/a

**Environment**

- OS:       Windows 10 Pro
- Device:   PC
- Version:   6.13.21
- Working Version: n/a

**Additional context**
My best guess as to what's going on is that some updates are sneaking in between the lock being released in `ObservableCache.Connect()`, in which the `initial` snapshot is created, and the returned observable being subscribed to.

Best wishes & thanks for creating this library.
Chris.

**Comment by RolandPheasant** [comment]
I am fairly sure this has been fixed via a related issue,

Please reopen if not, Thanks
