### ISSUE TITLE
No Removes from IObservable<IEnumerable<>>>

### ISSUE THREAD

**Issue by CaseNewmark** [reactivemarbles/DynamicData#326]
Hi,
I use `IObservable<IEnumerable<>>>.ToObservableChangeSet()` with a key selector to generate an observable cache. I'm not sure about the intended behavior here, but I expected that pushing an incomplete list through the observable would create a "Remove" event, which it doesn't.

-> list{{"a", 0}}  --> 1 Add
-> list{{"a", 1},{"b", 1}}  --> 1 Add, 1 Update
-> list{{"a", 2}}  --> 1 Update

On the last one I would have expected a "Remove" also. Is this wrong?
Daniel

**Comment by RolandPheasant** [comment]
The default option is simply to accumulate all. However, you make a good point that this behaviour is not desired. Having an option as included in the PR  is a good idea.

**Comment by rhy-ama** [comment]
More so if the IEnumerable<T> has T : IDisposable...

**Comment by RolandPheasant** [comment]
Fixed in linked PR
