### ISSUE TITLE
[Question] Clear and Remove performance improvements

### ISSUE THREAD

**Issue by hyuck1017** [reactivemarbles/DynamicData#338]
Hi~!

I am using dynamic data to develop a dynamic tree.

However, when removing or cleaning the SourceCache, it seems to be slower than I thought.

As a result of debugging, I confirmed that it takes time to filter, sort, and dispose of the object to be removed when the function is called.

In case of clear or remove, the object does not need filter or sorting.
Can it be prevented from being called?

Or you can increase the speed in other ways. Please let me know if there is a way.

Below is the way I am using

{
  var childNodes = this.Connect()
                .TransformToTree(item => item.ParentID)
                .Transform(item =>
                {
                    item.Item.InitializeChildNodes(item, itemFilter, sortParameters);
                    return item.Item;
                })
                .DisposeMany()                
                .Filter(searchFilter)
                .Sort(sort)
                .Bind(this.childNodes)
                .Subscribe();
}

Then please answer. Thank you.

**Comment by RolandPheasant** [comment]
> As a result of debugging, I confirmed that it takes time to filter, sort, and dispose of the object to be removed when the function is called.

What debugging did you do, how much data did you use, and did you batch your updates or do them one at a time?  

The only operator which I would say in intrinsically slow is Sort. Have you seen the [sort wiki](https://github.com/reactiveui/DynamicData/wiki/Sorting)?

**Comment by hyuck1017** [comment]
Sorry my explanation was lacking.

I put 8000 data in the SourceCache and called ObservableCacheEx.Clear().

At this time, 20 seconds were spent on my computer, 75% of which were object disposal, 25% filter, and sort function.

When deleting all with remove, the case was similar, and the key to be deleted was passed as a list argument and processed at once.

We need a way to get rid of it faster. So I looked for the cause of the load. This is the original performance
Is it right to come out? Or is there any way?

**Comment by RolandPheasant** [comment]
The last time I measured clear, it was very fast so I am not sure why it has become an issue. To help me investigate, can you please create a test project (not a UI project). Something which replicates your scenario with the bare minimum replication?

**Comment by hyuck1017** [comment]
I am using a simple test UI project. But I think I can make it simpler.
I will make it again and comment.

**Comment by hyuck1017** [comment]
@RolandPheasant 
I invited you to GitHub, which has a test project I made.

link. https://github.com/hyuck1017/DynamicDataSample

Please come here and check.

Thank you

**Comment by RolandPheasant** [comment]
I confirm that I can see a serious issue with performance in this case. However it is hard to isolate with your example. I will attempt to isolated it myself. However, it seems to almost certainly be caused by the `TransformToTree` operator

**Comment by hyuck1017** [comment]
Thank you very much for the code confirmation.
May the performance problem related to **transformtotree** be solved well
I hope. If the problem is fixed or otherwise,
If found, please let me know.

Thank you very much

**Comment by RolandPheasant** [comment]
If this is still an issue, please re-open
