### ISSUE TITLE
[BUG] WhenAnyValueChanged goes into a loop

### ISSUE THREAD

**Issue by FrancoisM** [reactivemarbles/DynamicData#347]
**Describe the bug**

WhenAnyValueChanged can notify infinitely some changes.

**Steps To Reproduce**

Here is a [repro ](https://github.com/FrancoisM/DynamicDataLoopIssue)with a test that shows the loop and another one without the loop which is identical except that the view model interface says that it implements IReactiveObject.

**Expected behavior**

No loop.

**Screenshots**

**Environment**

- OS:      Windows 10
- Device:   Desktop

**Comment by glennawatson** [comment]
Do you get the issue fixed if you use `INotifyPropertyChanged` instead of `IReactiveObject`. Just attempting to diagnose your issue a bit.

**Comment by FrancoisM** [comment]
Yes issue fixed with `INotifyPropertyChanged`. I used `IReactiveObject `by habit.
