### ISSUE TITLE
BindableDerivedListAttribute with a .BindEx( this, x => x.MyDerivedList) extension method

### ISSUE THREAD

**Issue by ChaseFlorell** [reactivemarbles/DynamicData#348]
**Is your feature request related to a problem? Please describe.**

I'm a huge fan of leveraging the Rx Fody attributes in order to make my app clean and terse. One area That I'd love to see further improvement is around derived lists. Currently my derived list code looks like this.

```csharp
ctor()
{
    this.WhenAnyValue(vm => vm.People)
        .Subscribe(people => people
            .ToObservableChangeSet()
            .AutoRefresh(x => x.Deleteed)
            .Filter(x => !x.Deleted)
            .Bind(out _visiblePeople)
            .Subscribe());
}

private ReadOnlyObservableCollection<Person> _visiblePeople;
public ReadOnlyObservableCollection<Person> VisiblePeople => _visiblePeople;
```
**Describe the solution you'd like**

What I'd love to be able to do is clean it up and remove the backing field

```csharp
ctor()
{
    this.WhenAnyValue(vm => vm.People)
        .Subscribe(people => people
            .ToObservableChangeSet()
            .AutoRefresh(x => x.Deleted)
            .Filter(x => !x.Deleted)
            .BindEx(this, x => x.VisiblePeople)
            .Subscribe());
}

public ReadOnlyObservableCollection<Person> VisiblePeople { [BindableDerivedList] get; };
```

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

**Additional context**

This would very much be akin to the existing ObservableAsPropertyAttribute

**Comment by glennawatson** [comment]
User wants a fody for dynamic data.

**Comment by RLittlesII** [comment]
@ChaseFlorell I think this is doable.  We have some work coming up soon around Fody.  So we can evaluate this when we target that work.

**Comment by RolandPheasant** [comment]
I am not sure what is required?  Is it still relevant? If so please reopen and let's discuss further.
