### ISSUE TITLE
feature: `TransformMany` overloads for observable cache

### ISSUE THREAD

**Issue by andersstorhaug** [reactivemarbles/DynamicData#351]
In [`ObservableCacheEx.cs`:2302](https://github.com/reactiveui/DynamicData/blob/master/src/DynamicData/Cache/ObservableCacheEx.cs#L2302), overloads for `TransformMany` that work against the following are currently commented out / unfinished:
- `IObservable<IChangeSet<TDestination, TDestinationKey>>>`
- `IObservableCache<TDestination, TDestinationKey>>`

Is the implementation simply just not finished yet, or are there issues that prevent these from being implemented?

I've ran across some situations where I think these overloads would be useful.
For instance, to flatten out groups, the  `IObservable<IChangeSet<TDestination, TDestinationKey>>>` version could be used:

```csharp
// `Group` + `InnerJoin` is the same as `InnerJoinMany`, but it uses a cache internally
// I'm assuming that the key selector is still going to be necessary

// Result: cache of `(Parent, Child)` by child ID
// Produces the same result as a SQL inner join with 1:N cardinality
var childrenWithParents = childrenCache.Connect()
    .Group(x => x.ParentId)
    .InnerJoin(parentCache.Connect(), x => x.Id, (children, parent) => (Children: children.Cache, Parent: parent))
    .Transform(parentChildren => parentChildren.Children.Connect().Transform(child => (parentChildren.Parent, Child: child)))
    .TransformMany(x => x, x => x.Child.Id)
    .AsObservableCache();
```

**Comment by andersstorhaug** [comment]
Also, if there's a currently a better / alternative way to do this, please let me know.

The desired result is a flattened 1:N inner join between caches.

**Comment by RolandPheasant** [comment]
The commented out code I think was a mistake. My usual policy is to remove all commented out code but those slipped the net. I cannot remember exactly why they were there in the first place but I think using an overload of `TransformMany` was my first attempted solution to joins. When I realised this did not work perfectly I wrote the specialised operators 

Is there any issue with `InnerJoinMany`?

**Comment by andersstorhaug** [comment]
That makes sense.

My difficulty with `InnerJoinMany` is that when I have multiple levels of many joins, I end up with nested collections, and that is hard to consume.

The following produces the desired result with existing operators, but when a child is added, every child with the same parent will receive a superfluous update.

```csharp
var childrenWithParent = parentCache.Connect()
    .InnerJoinMany(childCache.Connect(), x => x.ParentId, (parent, children) => (parent, children))
    .TransformMany(x => x.children.Items.Select(child => (parent, child)), x => x.child.Id)
    .AsObservableCache();
```

So, that's why I started looking into this alternative:

```csharp
var childrenWithParent = childCache.Connect()
    .Group(x => x.ParentId)
    .InnerJoin(parentCache.Connect(), x => x.Id, (children, parent) => (children, parent))

    // No versions that work with `IObservableCache<TSource, TKey>` or `IObservable<IChangeSet<TSource, TKey>>
    .TransformMany(???)
    .AsObservableCache();
```

Hope the use-case makes sense.

This may be better handled by a new join operator.. `InnerJoinManyFlat` / `LeftJoinManyFlat`.

**Comment by andersstorhaug** [comment]
OK, I've been able to implement this idea of a flattened join... see this [gist](https://gist.github.com/andersstorhaug/ffd95845c56af23350a549ae31e9410a).

The desire to have something like this has come up often enough for me, that I'd think others might like to have this functionality baked-in to the library as well.

Just not sure about how to pull it into the library -- thoughts?

**Comment by andersstorhaug** [comment]
On second thought... I'm not really sure what to call this.

It is like the existing `InnerJoinMany`, but from the other side, where there are many left items to one right item.

Call it `ManyInnerJoin`? No idea..

**Comment by andersstorhaug** [comment]
[Here's a gist](https://gist.github.com/andersstorhaug/76122879f6ddc353cf38fcc7fc1e2f95) of something that's a little closer to an acceptable implementation for the library.

Should I think about opening a PR and continuing a discussion there?

**Comment by RolandPheasant** [comment]
I think this would make a great PR. If you push it with unit tests, I can pull your  branch and do some further experimentation to work out what the best solution to the mentioned issue.

I am not sure about the name. Stick with what you have and we can easily change before deployment.

**Comment by RolandPheasant** [comment]
Are you still interested in raising a PR?
