### ISSUE TITLE
feature: ToZeroOneChangeSet

### ISSUE THREAD

**Issue by ronaldvdv** [reactivemarbles/DynamicData#356]
In many cases, I want to convert a normal `IObservable<T>` into an `IObservable<IChangeSet<T>>` for use with DynamicData operators. I'm using a temporary solution for now, see below.

- Would it make sense to add this operator to the DynamicData source (happy to provide a pull request in that case)?
- When using `TransformMany` on top of this method, I notice "replace" changes lead to problems down the pipeline so I've added a parameter that makes the operator use remove/add instead of replace changes. If you have a nicer solution to this, I would be happy to update the operator below.

```csharp
    internal class ToZeroOneChangeSet<T>
    {
        private readonly IObservable<T> _source;
        private readonly bool _useReplacements;

        public ToZeroOneChangeSet(IObservable<T> source, bool useReplacements = true)
        {
            _source = source ?? throw new ArgumentNullException(nameof(source));
            _useReplacements = useReplacements;
        }

        public IObservable<IChangeSet<T>> Run()
        {
            return Observable.Create<IChangeSet<T>>(observer =>
            {
                var comparer = EqualityComparer<T>.Default;

                var latest = default(T);
                return _source
                .Where(value => !comparer.Equals(latest, value))
                .Select(value =>
                {
                    var changes = new ChangeSet<T>();
                    if (_useReplacements && latest != null && value != null)
                    {
                        changes.Add(new Change<T>(ListChangeReason.Replace, value, latest, 0));
                    }
                    else
                    {
                        if (latest != null)
                            changes.Add(new Change<T>(ListChangeReason.Remove, latest, 0));
                        if (value != null)
                            changes.Add(new Change<T>(ListChangeReason.Add, value, 0));
                    }
                    latest = value;
                    return changes;
                }).SubscribeSafe(observer);
            });
        }
    }
```

**Comment by RolandPheasant** [comment]
Hi, can you please provide an example of expected inputs and outputs so that I can understand what this operator does? Thanks

**Comment by ronaldvdv** [comment]
I guess this is best summarized in the following table.

| First source value | Second source value | `useReplacements` | Changeset |
|---|---|---|---|
| null | null | - | *Nothing* |
| null | A | - | Add: A |
| A | null | - | Remove: A |
| A | B | true | Replace: A->B |
| A | B | false | Remove: A ; Add B |

The goal is to be able to treat the `IObservable<T>` source stream as a changeset for a collection containing zero or one elements.

**Comment by RolandPheasant** [comment]
I'll close this as it seems to not be a wide issue. 

However I am curious to know what effect the following statement alludes to.

> I notice "replace" changes lead to problems down the pipeline
