### ISSUE TITLE
Change in behaviour of ToObservableChangeSet with expireAfter in v6.14.*

### ISSUE THREAD

**Issue by aguahombre** [reactivemarbles/DynamicData#358]
The ToObservableChangeSet expireAfter no longer works in v6.14.* if the the source IObservable<IEnumerable<T>> completes before the timeout occurs.

Using this example compiled with v6.13.21 using .netcore 3.1 console program on Windows 10
```
static void Main(string[] args)
{
    Observable.Return(Enumerable.Range(0, 10).Select(i => new { A = i, B = 2 * i }))
        .ToObservableChangeSet(x => x.A, _ => TimeSpan.FromSeconds(5))
        .Subscribe(x => Console.WriteLine($"{DateTime.UtcNow} {x.Count}:\n  {string.Join("\n  ", x)}"));
    Console.ReadKey();
}
```

produces the output
![image](https://user-images.githubusercontent.com/17591364/81317364-a82fa900-9084-11ea-99ef-068d8cd9380d.png)

but with v6.14.18
![image](https://user-images.githubusercontent.com/17591364/81317597-f47ae900-9084-11ea-8333-783ac740c9ca.png)

I would expect the v6.13.21 behaviour to occur; i.e. the items to be removed from the change set after 5 seconds.

**Comment by RLittlesII** [comment]
@aguahombre Thank you for providing this report.  We will look into it and provide and update.

Also, is there a list of dependent libraries and their versions per test execution?

**Comment by aguahombre** [comment]
Here is the project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" Version="6.14.18" />
  </ItemGroup>

</Project>
```

and the using statements
```
using System;
using System.Linq;
using System.Reactive.Linq;
using DynamicData;
```

**Comment by RolandPheasant** [comment]
It's been long overdue for me looking at this. But the change which creates there error was introduced [in the commit](https://github.com/reactivemarbles/DynamicData/commit/774363521988d68f917f99a51a8845192235f006).

It's not obvious why this would be an issue but I'll take a look.  Ideally it can be reproduced in a unit test.
