### ISSUE TITLE
ObsevableCache.Connect prevents initial change set being GCed

### ISSUE THREAD

**Issue by aguahombre** [reactivemarbles/DynamicData#359]
While trying to track down the source of a memory leak of a large ChangeSet containing many items, I discovered that the leaked change set was the initial change set output by the ObsevableCache.Connect call. On investigating the implementation of ObsevableCache.Connect I found that it uses Observable.Return to pass the initial change set. A side affect of Observable.Return is that it retains a reference to its value parameter (i.e. the initial change set) hence the initial change set cannot be GCed for the life of observable cache subscription. When using ObsevableCache.Connect on a large cache the initial change set could have many thousands of items, all prevented from being GCed.

I believe a fix would be to replace Observable.Return with Observable.Create so that no reference is retained to the initial change set.

Here is repo:
```
using System;
using System.Linq;
using System.Reactive.Linq;
using DynamicData;

namespace ObservableReturn
{
    class Program
    {
        static void Main(string[] args)
        {
            var cache = new SourceCache<MyItem, int>(x => x.Key);
            cache.AddOrUpdate(Enumerable.Range(0, 10).Select(i => new MyItem { Key = i, Value = $"This is part of the initial change set {i}" }));

            var subscription = cache.Connect()
               .Subscribe(x => Console.WriteLine(x));

            cache.AddOrUpdate(new MyItem { Key = 100, Value = "This is added after subscription" });

            GC.Collect();
            Console.ReadKey();
            subscription.Dispose();
            GC.Collect();
            Console.ReadKey();
        }

        class MyItem
        {
            public int Key { get; set; }
            public string Value { get; set; }
            public override string ToString() => $"{Key}: {Value}";
        }
    }
}
```

Here is a memory dump taken at the first ReadKey showing the initial change set of 10 items has not been GCed but the subsequent change set has been. Note the zero length change set is probably a static Empty change set generated by the DynamicData assembly?
![image](https://user-images.githubusercontent.com/17591364/81660610-e20d0080-9432-11ea-94ca-c889258ce1bb.png)

Only after the subscription is disposed at the second ReadKey is the initial change set of 10 items is GCed.
 
![image](https://user-images.githubusercontent.com/17591364/81661226-b50d1d80-9433-11ea-8bbd-9993ef0e04b5.png)

I would expect the initial change set to be GCed at the next collection after it has passed through the observable sequence; i.e. at the first ReadKey in the example code.

It would be worth checking if this problem also exists for ObservableList.

DynamicData v6.14.18
Windows 10
Dotnet Core 3.1 console app.

**Comment by RolandPheasant** [comment]
Hmm, there's nothing obvious in DD which is rooting the change sets. However I can confirm your findings by running the about  through a profiler.

I will look deeper.

**Comment by aguahombre** [comment]
I raised this with the RX team. I asked why Observable.Return keeps a copy of the return value for the lifetime of the observable. The answer:

An observable can be subscribed to any number of times. So Observable.Return must hold on to the value, it can't null it at any time. Also, it obviously can't determine that it's only going to be subscribed to once.

Obvious once explained. So the Observable.Return lifetime is determined by the ,Concat so the initial changeset lives until the whole observable sequence is disposed.

An unexpected side affect of using Observable.Return that is not documented.

**Comment by RolandPheasant** [comment]
That explains it clearly thanks.

I'll check for any other problematic usages of `Observable.Return` and get rid of them.

**Comment by bddckr** [comment]
Note: #377 did seemingly resolve this issue for `ObservableCache`, but we're missing the same adjustment to `LockFreeObservableCache` still as far as I can see. I just wanted to note this here 🙂
