### ISSUE TITLE
How to stream data using dynamicData

### ISSUE THREAD

**Issue by ben1628** [reactivemarbles/DynamicData#362]
In my case, I'm loading a fairly large collection from a database. like this.
```csharp
IEnumerable<TestProp> myList ()
{
var TestRecords = from db.Test group by Date;
select 
{
Date,
Max,
Min
}
foreach (item in TestRecords)
{
    yield return item;
}
}
```
I am hoping that it will return one item at a time back to my viewModel, and I can consume it this way.

```csharp
IEnumerable<TestProp> myList = vmMwt.LoadAvailableData(...)
            AvailableDataList.Edit(innerList =>
            {
                innerList.Clear();
                innerList.AddRange(myList);
            }
            );

            AvailableDataList.Clear();
            AvailableDataList.Edit(innerList =>
            {
                // innerList.Clear();
                Debug.Print("StockDate: " + myList.Count());
                innerList.Add(myList);
            }
            );

            _AvailableDataCollection.Clear();
            AvailableDataList.Connect()
               .Buffer(TimeSpan.FromMilliseconds(250)).FlattenBufferResult()

                .ObserveOn(RxApp.MainThreadScheduler)
               //  .ObserveOnDispatcher()
               .Bind(_AvailableDataCollection)
               .DisposeMany()
               .Subscribe();
```

It seems that it will wait until all records are loaded before it populating the gird using this

```csharp
            this.OneWayBind(VM, vm => vm.AvailableDataCollection, v => v.sfAvailable.DataSource);
```

I was hoping that grid will show up and each record will be stream to the grid as it becomes available.

Any help and suggestion would be greatly appreciated.

**Comment by RLittlesII** [comment]
Updated comment to use MD syntax for readability.

**Comment by RolandPheasant** [comment]
It's better to ask these questions on slack. Are you a member? If not, you can join here https://reactiveui.net/slack

**Comment by sa-he** [comment]
According to my understanding `AvailableDataList.Edit` is intended to be a bulk edit which leads exactly to your described result.

Instead try this (untested):

    // make sure to first bind
    AvailableDataList.Connect()
       .Buffer(TimeSpan.FromMilliseconds(250)).FlattenBufferResult()
        .ObserveOn(RxApp.MainThreadScheduler)
        .Bind(_AvailableDataCollection)
        .DisposeMany() // question sure you want to dispose your loaded items?
        .Subscribe();

    // Then, add your items one by one in a background thread to allow the main thread updating the UI.
    Task.Run(()=>
    {
        foreach item in myList
        {
            AvailableDataList.Add(item);
        }
    });
