### ISSUE TITLE
ChangeAwareList.AddRange add wrong index to changes

### ISSUE THREAD

**Issue by KAS1990** [reactivemarbles/DynamicData#372]
**Describe the bug**
ChangeAwareList.AddRange generate wrong CurrentIndex in ItemChange<T>.

**Steps To Reproduce**
`SourceList<T> source = new SourceList<T>();
source.Connect().ForEachItemChange(ch => Debug.WriteLine(ch.CurrentIndex)).Subscribe();
source.Edit(list => list.AddRange(new T[] { new T() }));
source.Edit(list => list.AddRange(new T[] { new T() }));`

Output will be:
0
0 // WTF?

If i call list.Add(new T()) instead of list.AddRange(new T[] { new T() }) output is
0
1

**Expected behavior**
 Second behavior is correct.

**Environment**
- OS:       Windows 10 Pro 1909 18363.900
- Device:   PC
- Version:  6.13.0.0

The problem in method ChangeAwareList.AddRange. It create Change<T> with wrong parameters
`var args = new Change<T>(ListChangeReason.AddRange, collection);`
It does not pass index, therefore it set as -1:
`public Change(ListChangeReason reason, IEnumerable<T> items, int index = -1)
{
...
}`
ForEachItemChange uses ItemChangeEnumerator. ItemChangeEnumerator.GetEnumerator() uses this index:
`index = change.Range.Index == -1 ? lastKnownIndex : change.Range.Index;`
change.Range.Index always -1 => index always starts with 0, because lastKnownIndex starts with 0 too.

**Comment by KAS1990** [comment]
I have found the solution. There is extension method ListEx.AddRange which has parameter index. If i pass list.Count to it, ForEachItemChange generate correct CurrentIndex. But the behavior of original AddRange is strange.

**Comment by glennawatson** [comment]
Sounds good, thanks for tracking that down. 

Would you be interested in doing a pull request, with your test code above as a unit test?

**Comment by KAS1990** [comment]
Yes. You can commit changes and then i pull it and test.

**Comment by RolandPheasant** [comment]
I've made this change but cannot confirm whether whether your exact issue is fixed because of the lack of reproducible code presented.
