### ISSUE TITLE
[BUG] NuGet package leaks ReSharper annotation classes

### ISSUE THREAD

**Issue by TheCatPlusPlus** [reactivemarbles/DynamicData#384]
**Describe the bug**

Not a functional bug, but a packaging issue: `DynamicData` assembly in the NuGet packages contains ReSharper annotation attributes with public visibility (`DynamicData.Annotations`). And because the namespace is alphabetically before `JetBrains.Annotations`, ReSharper tends to want to import it instead when writing out annotations. It's not a huge deal, but still happens often enough to be mildly annoying.

**Steps To Reproduce**

Create an empty project referencing the package:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" Version="6.16.1" />
  </ItemGroup>

</Project>
```

```
using DynamicData.Annotations;

[UsedImplicitly]
public class Class1
{
}
```

**Expected behavior**

Private versions of these attributes should have internal visibility and the above example shouldn't compile.

The annotations are also available via [`JetBrains.Annotations`](https://www.nuget.org/packages/JetBrains.Annotations) package, so it might also be worth migrating to that instead of embedding them in a custom namespace. This is probably a better way to go if they're preserved in the assembly intentionally and not accidentally, as downstream projects are likely to be using the official namespace and not want the duplicates.

**Environment**
- Version: 6.16.1
- Target: netstandard2.0 (possibly others as well)

**Comment by RolandPheasant** [comment]
These were removed some time back so the problem should have gone away.
