### ISSUE TITLE
feature: Add ovveride Edit method

### ISSUE THREAD

**Issue by kronic** [reactivemarbles/DynamicData#390]
**Is your feature request related to a problem? Please describe.**
Yes. Remove delegate allocation
**Describe the solution you'd like**
Add method override
```csharp 
SourceCache<TObj,TKey>
void Edit<TState>(Action<ISourceUpdater<TObject, TKey>, TState> updateAction, TState state); 
```
Add method override
```csharp 
SourceList<T>
void Edit<TState>(Action<ISourceUpdater<T>, TState> updateAction, TState state); 
```
**Describe alternatives you've considered**
No
**Describe suggestions on how to achieve the feature**
No
**Additional context**
No

**Comment by glennawatson** [comment]
Your after the ` character which is a little hard on the european keyboard apparently.

**Comment by kronic** [comment]
@glennawatson Now it's normal

**Comment by RolandPheasant** [comment]
I understand that this would save an allocation, however I am not sure whether any benefits would be tangible considering most allocations comes from change set creation and these are much greater than the benefit of the complex change of changing the signature.

That said, I would accept a PR.  So if anyone wants to do so, please re-open this.
