### ISSUE TITLE
[BUG] Sort crashes on a SourceList, which is composed out of multiple SourceLists through MergeMany, after Reset

### ISSUE THREAD

**Issue by HrlecMatej** [reactivemarbles/DynamicData#397]
**Describe the bug**

When sorting a SourceList, which is composed out of multiple SourceLists through MergeMany, an exception can happen if a big change triggers the resetThreshold.
The following example can easily reproduce the bug and the following exception.

**Steps To Reproduce**

```
SourceList<int> firstSource = new SourceList<int>();
SourceList<int> secondSource = new SourceList<int>();
SourceList<SourceList<int>> mergedSource = new SourceList<SourceList<int>>();

mergedSource.Connect()
	.MergeMany(innerSource => innerSource.Connect())
	// I set resetThreshold to 2, so I don't need as many changes to trigger Sort.Reset()
	.Sort(SortExpressionComparer<int>.Ascending(x => x), resetThreshold: 2)
	.ToCollection()
	.Subscribe(indices =>
	{
		Debug.WriteLine("###############");
		foreach (int index in indices) Debug.Write(index);
		Debug.WriteLine("");
	});

mergedSource.Add(firstSource);
mergedSource.Add(secondSource);

firstSource.Add(0);
firstSource.Add(1);
firstSource.Add(2);
firstSource.Add(3);
secondSource.Add(4);
secondSource.Add(5);
secondSource.Add(6);
secondSource.Add(7);

// Start removing index numbers by, well... indices
// Should remove 3
firstSource.RemoveAt(3);
// Should remove 0, 1, 2
firstSource.RemoveRange(0,3);
// Because the number of changes (3) is higher than the resetThreshold (2), the following happens:
// In Sort.Run(), List "orginal" gets used to reset the "target"
// Since "orginal" does not Clone correctly, this messes up the resulting "target"

// After reset:
// Expected collection: 4, 5, 6, 7
// Actual result: 3, 4, 5, 6

// That means, the following line crashes the application
secondSource.RemoveAt(3);
// DynamicData.SortException: 'Cannot find item: ObjectWithIndex -> Inel.Rx.Notification.Standard.ObjectWithIndex'
```

**Output of my example**
###############
0
###############
01
###############
012
###############
0123
###############
01234
###############
012345
###############
0123456
###############
01234567
###############
0124567
###############
3456
Exception thrown: 'DynamicData.SortException' in DynamicData.dll
Cannot find item: ObjectWithIndex -> Inel.Rx.Notification.Standard.ObjectWithIndex

**Why this happens and solution**
The bug happens because "orginal" is not correctly updated with changes, when more than 1 SourceList is used, e.g. it will quickly fail in situations where MergeMany is used.
Issue lies in the method DynamicData.ListEx.Clone<T>(this IList<T> source,  Change<T> item, IEqualityComparer<T> equalityComparer)

Because of my example, I'll explain the case ListChangeReason.Remove (line 181 in ListEx.cs):
```
// "change" is the item that has been removed 
var change = item.Item;
// Here is the issue. 
// "CurrentIndex" is the index of the object in the inner source, in our example "firstSource"
bool hasIndex = change.CurrentIndex >= 0;
if (hasIndex)
{
	// But this line removes the object at the index in the merged source
	// The problem is, the object might not be (and in our case it isn't) in the same place
	// This line then actually removes the object with index 3 in "secondSource" ...
	source.RemoveAt(change.CurrentIndex);
	// Once Sort.Reset() is called, this garbled "orginal" List is used to sync with "target"
	// The result has wrong items left in it, with incorrect indexes. 
	// At that point an Expection is easy to trigger.
}
```

Possible solution:
This issue repeats itself over some other ListChangeReasons, so I'll again just show Remove:
```
T current = item.Item.Current;
int currentIndex = item.Item.CurrentIndex;
int realIndex = -1;

bool hasIndex = currentIndex >= 0;
if (hasIndex)
{
	T potentialCurrent = source[currentIndex];
	// Since we have an index, we want to do an additional check
	// Is "potentialCurrent" same as "current" ?
	// It might not be, if our backing source is made out of multiple sources from MergeMany
	bool isIndexCorrect = equalityComparer?.Equals(current, potentialCurrent) ?? current.Equals(potentialCurrent);
	if (isIndexCorrect) realIndex = currentIndex;
}
if (realIndex == -1)
	realIndex = equalityComparer == null ? source.IndexOf(current) : source.IndexOf(current, equalityComparer);

source.RemoveAt(realIndex);

break;
```

This kind of a fix is needed for some of the other ListChangeReasons as well.

Alternatively, looking up indices could be skipped in favor of the approach from ProcessImpl Sort.cs line 78. There the "current" object is always handled by reference, not by the index in change.Item.CurrentIndex. This probably has a performance impact though (in which case ProcessImpl should probably be rewritten too). Also, in any case, GetCurrentPosition from Sort.cs should be probably used in ListEx as well, so that BinarySearch can potentially be used.

As an extra note, Sort.cs uses _comparer inconsistently, e.g.:
```
var index = _sortOptions == SortOptions.UseBinarySearch
	? target.BinarySearch(item, _comparer) // comparer used
	: target.IndexOf(item); // comparer not used, even though an overload exists for it
```
Another inconsistency, comparer is marked as [NotNull], even though there is a Sort overload, that sets it to null. As a consequence, null checks are performed on the "NotNull" comparer...

**Workaround**
Set resetThreshold to int.MaxValue, so that Reset never triggers. This does mean "orginal" will still keep getting updated in the background.
Setting resetThreshold to 1 or less doesn't work, because that just means Reset gets triggered constantly, which completely messes up everything (this probably counts as a bug as well).
```
changes.TotalChanges > _resetThreshold && _comparer!=null ? Reset(orginal, target) : Process(target, changes)
```
There should be a way to turn off reseting, e.g. by having a resetThreshold of 0 or less skip reset part of the code.

**Pull request**
If suggested changes seem okay with others, I can create a pull request where I attempt to fix:
- indexing issues in ListEx and Sort, by first attempting to retrieve an object by index O(1), then by BinarySearch O(log n) if enabled, only then by IndexOf O(n)
- use _comparer everywhere where possible
- turn off reset if _resetThreshold 0 or less

**Environment**

- OS: Windows 10      
- Device: PC  
- Version: 6.16.3  
- Working Version:

**Comment by HrlecMatej** [comment]
As I have said, if I can get any feedback on my proposal, I could prepare a pull request.

**Comment by RolandPheasant** [comment]
Finally got around to analysing the code above. Have you considered (or tried) using the logical `Or` operator?

`
 var logicallyCombined = mergedSource.Connect().Or();
`

It is a specialisation which includes items which in any of the child collections. The difference when compared to using `MergeMany` is that it also handles the case of removing items which were held by a sub collection when a sub collection is removed.

**Comment by HrlecMatej** [comment]
Is there a way to remove a collection from the mergedSource as well?

**Comment by HrlecMatej** [comment]
So, if I changed it like this, it does indeed work.
```cs
SourceList<int> firstSource = new SourceList<int>();
SourceList<int> secondSource = new SourceList<int>();
SourceList<ISourceList<int>> mergedSource = new SourceList<ISourceList<int>>();

mergedSource.Add(firstSource);
mergedSource.Add(secondSource);

mergedSource.Or()
	.Sort(SortExpressionComparer<int>.Ascending(x => x), resetThreshold: 2)
	.ToCollection()
	.Subscribe(indices =>
	{
		Debug.WriteLine("###############");
		foreach (int index in indices) Debug.Write(index);
		Debug.WriteLine("");
	});
```

Though I am using this merging in our application under a heavy load, and there's some issues with Or.
It can freeze the whole application, if we Add an entry to an inner SourceList at the same time we remove it from the merged list (we have asynchronous operations).
If we use locks around operations, the order of entries from inner SourceLists still gets all messed up.

**Comment by RolandPheasant** [comment]
Regarding the freezing, that sounds like UI thread blocks.  With such a low threshold, the ui will constantly be rebinding which is almost certainly causing issues.  Have you tried a higher threshold?

Also you could add a `.Batch(Timespan.FromMilliseconds(x))` after  `Or` to try and smooth out updates and give the UI time to respond.  Is it possible for you to replicate the remaining issues in either a console app or in unit test code?

**Comment by HrlecMatej** [comment]
My service is a bit long, but I added a way to generate a lot of inputs, and in the end, remove and readd whole SourceLists.
For context, I use dynamic data to display a list of logs, and a user has buttons to turn a log type on or off.
The whole UI always freezes after the first or second readd for whatever reason.
Also, unlike MergeMany, I cannot add or remove SourceLists in an async method, because one of two things happens. The log freezes (similar to the scenario I described above) or an exception triggers: System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'
About MergeMany, I have been using the implementation [described in this blogpost](https://blog.magentaize.xyz/posts/mergemany-do-not-remove-elements-of-removed-observables-in-dynamicdata/), because the default MergeMany doesn't remove old entries from the merged source when a SourceList is removed. As described in my issue, I also set the reset threshold to Int.MaxValue, so the reset logic never triggers.

My guess is Or is not thread-safe, unlike MergeMany?

Example with Or:
```cs
public enum NotificationType
{
	Error = 1,
	Warning,
	Info,
	Debug
}
	
public class NotificationService
{
	private readonly SourceList<ISourceList<NotificationItem>> _currentlyVisibleNotifications =
		new SourceList<ISourceList<NotificationItem>>();

	private readonly Dictionary<NotificationType, SourceList<NotificationItem>> _notifications =
		new Dictionary<NotificationType, SourceList<NotificationItem>>();

	/// <summary>
	///     Use this service to generate UI notifications.
	/// </summary>
	public NotificationService(IOptions<NotificationConfiguration> notificationConfig)
	{
		foreach (NotificationType notificationType in Enum.GetValues(typeof(NotificationType)))
		{
			var notificationSourceList = new SourceList<NotificationItem>();
			_notifications[notificationType] = notificationSourceList;
			_currentlyVisibleNotifications.Add(notificationSourceList);
		}

		Observable.Interval(TimeSpan.FromMilliseconds(21))
			.Subscribe(_ => NotifyError("An egregious error"));

		Observable.Interval(TimeSpan.FromMilliseconds(22))
			.Subscribe(_ => NotifyWarning("A hounding warning"));

		Observable.Interval(TimeSpan.FromMilliseconds(23))
			.Subscribe(_ => NotifyInformation("A piece of valuable information"));

		Observable.Interval(TimeSpan.FromMilliseconds(24))
			.Subscribe(_ => NotifyDebug("An important debug message"));

		Observable.Timer(TimeSpan.FromSeconds(20))
			.Subscribe(async _ =>
			{
				Debug.WriteLine("Start simulating UI actions");
				MakeNotificationTypeHidden(NotificationType.Error);
				await Task.Delay(1000);
				MakeNotificationTypeVisible(NotificationType.Error); // freezes here
				await Task.Delay(1000);
				MakeNotificationTypeHidden(NotificationType.Warning);
				await Task.Delay(1000);
				MakeNotificationTypeVisible(NotificationType.Warning); // or here
			});
	}

	/// <summary>
	///     Visible notifications are merged from all notification types (as denoted by NotificationType) that are currently
	///     enabled.
	///     The method connects and returns the top {LimitOfNotificationEntries} number of entries, sorted by time and index.
	/// </summary>
	/// <returns></returns>
	public IObservable<IChangeSet<NotificationItem>> ConnectToVisibleNotifications =>
		_currentlyVisibleNotifications.Or()
			.Sort(SortExpressionComparer<NotificationItem>.Descending(x => x.Time).ThenByDescending(x => x.Index),
				SortOptions.UseBinarySearch);

	public IObservable<IChangeSet<NotificationItem>> ConnectToNotification(NotificationType notificationType) =>
		_notifications[notificationType].Connect();

	private void Notify(NotificationType notificationType, string error)
	{
		if (!_notifications.ContainsKey(notificationType)) return;

		NotificationItem notificationItem = notificationType switch
		{
			NotificationType.Error => new NotificationItemError(error),
			NotificationType.Warning => new NotificationItemWarning(error),
			NotificationType.Info => new NotificationItemInfo(error),
			NotificationType.Debug => new NotificationItemDebug(error),
			_ => throw new ArgumentOutOfRangeException(nameof(notificationType), notificationType, null)
		};

		SourceList<NotificationItem> notification = _notifications[notificationType];
		notification.Add(notificationItem);
	}

	public void NotifyError(string error) => Notify(NotificationType.Error, error);
	public void NotifyWarning(string warning) => Notify(NotificationType.Warning, warning);
	public void NotifyInformation(string information) => Notify(NotificationType.Info, information);
	public void NotifyDebug(string debug) => Notify(NotificationType.Debug, debug);

	public void MakeNotificationTypeVisible(NotificationType notificationType) => 
		_currentlyVisibleNotifications.Add(_notifications[notificationType]);

	public void MakeNotificationTypeHidden(NotificationType notificationType) =>
		_currentlyVisibleNotifications.Remove(_notifications[notificationType]);
}

// How I connect to the notifications
notificationService.ConnectToVisibleNotifications
	.ObserveOn(RxApp.MainThreadScheduler)
	.Bind(out Notifications)
	.DisposeMany()
	.Subscribe();
```

**Comment by HrlecMatej** [comment]
> 
> 
> Regarding the freezing, that sounds like UI thread blocks. With such a low threshold, the ui will constantly be rebinding which is almost certainly causing issues. Have you tried a higher threshold?
> 
I am using Int.MaxValue as the threshold with MergeMany, since reset logic is bugged. The issue just presents an easy way to replicate the problem and get an exception

**Comment by HrlecMatej** [comment]
I have done a bunch more testing. I have updated my example to use locks and Tasks, and it works completely fine, IF I remove the .Top(LimitOfNotificationEntries).
That particular command breaks down sorting after just a few thousands entries (The limit is set high enough, that the program never comes close to reaching it during my tests). By that I mean entries start getting grouped in by type. It basically looks like it's not able to keep up.
Probably the crux of the problem with Top is how much CPU it uses. Putting that method in (which isn't actually doing anything, since it's way too high), triples the CPU usage. Meaning there seem to some big performace issues with Top implementation.

**Comment by HrlecMatej** [comment]
I will close this issue, since I encountered the problem a long while ago, and it might not be relevant anymore.
