### ISSUE TITLE
[BUG] Filter does not propagate removal change

### ISSUE THREAD

**Issue by dnm240** [reactivemarbles/DynamicData#407]
**Describe the bug**
The Filter extension method does not propagate Change(s) with ChangeReason.Remove.  This results in downstream collections not receiving the "Remove", thus incorrectly retaining items.

The method in question, from ObservableCacheEx:
public static IObservable<IChangeSet<TObject, TKey>> Filter<TObject, TKey>(this IObservable<IChangeSet<TObject, TKey>> source, Func<TObject, bool> filter)

**Steps To Reproduce**
Run the following code:
`[Test]`
`public void FilterDoesNotPropagateRemoveChange()`
`{`
`    var subject = new Subject<IChangeSet<string, int>>();`
`    subject.Filter(x =>`
`                   {`
`                       Console.Out.WriteLine("Filter false called"); // Expect to see this printed, but it is not`
`                       return false;`
`                   })`
`           .Subscribe(x => Console.Out.WriteLine($"Filter false result {x}")); // Do not expect to see this printed`
`    subject.Filter(x =>`
`                   {`
`                       Console.Out.WriteLine("Filter true called"); // Expect to see this printed, but it is not`
`                       return true;`
`                   })`
`           .Subscribe(x => Console.Out.WriteLine($"Filter true result {x}")); // Expect to see this printed, but it is not`
`    subject.Subscribe(x => Console.Out.WriteLine($"No filter result {x}")); // Expect to see this printed, and it is`
`    var change = new Change<string, int>(ChangeReason.Remove, 1, "A");`
`    var changeSet = new ChangeSet<string, int>(new []{change});`
`    subject.OnNext(changeSet);`
`}`

**Actual behavior**
My filter code is not called, and no ChangeSet is delivered.
`No filter result ChangeSet<String.Int32>. Count=1`

**Expected behavior**
My filter code should be called, and if the Remove Change passes my filter, a ChangeSet containing that Change should be delivered.
`Filter false called`
`Filter true called`
`Filter true result ChangeSet<String.Int32>. Count=1`
`No filter result ChangeSet<String.Int32>. Count=1`

**Environment**
- OS:       Windows 10 Pro 1903
- Device:   x64 Desktop PC
- Version:   6.16.3
- Working Version:

**Comment by RolandPheasant** [comment]
This is the expected behaviour.  The reason for the filter not being called is due to `ChangeReason.Remove`. Since the item was never added, there is noting to remove and therefore the filter lamda is not invoked.
