### ISSUE TITLE
Feature: Consistent FilterOnObservable, SortOnObservable, GroupOnObservable for List and Cache like FilterOnObservable

### ISSUE THREAD

**Issue by KeilFelix** [reactivemarbles/DynamicData#409]
Please consider providing these additional extension methods:

- FilterOnObservable (already available for IChangeSet&lt;TObject&gt; but not for IChangeSet&lt;TObject, TKey&gt;
- SortOnObservable
- GroupOnObservable

If you think the desired behavior is not clear from the method names, I can specify it further.

Further suggestion is to ditch the "OnObservable" and just have them as overloads.

**Comment by RolandPheasant** [comment]
Filter and Sort already have these overloads (without the OnObservable).

Regarding group, I am not sure how the c# type system could handle grouping on different keys?

**Comment by KeilFelix** [comment]
@RolandPheasant Maybe I don't understand how to achieve the same functionality with the overloads you mentioned. But none of the overloads uses a `Func<TObject, IObservable<bool>> objectFilterObservable` like the FilterOnObservable-method.

Sample imagine an `ISourceList<IDevice>` or  Cache

```
    public interface IDevice
    {
        IObservable<bool> IsOnline { get; }
        IObservable<int> Priority { get; }
    }
```

I want to Sort/Filter/Group based on the properties inside

**Comment by RolandPheasant** [comment]
I am considering marking FilterOnObservable as obsolete as it an awful operator beset with problems.  There is nothing it does which cannot be achieved by other means.

So closing this.
