### ISSUE TITLE
Stale Data in DynamicData.Binding.ObservablePropertyFactoryCache causes Exception

### ISSUE THREAD

**Issue by 8** [reactivemarbles/DynamicData#434]
## Summary
Stale Data in `DynamicData.Binding.ObservablePropertyFactoryCache` causes `System.InvalidCastException` exception when reloading a Type with the same name.

## Problem
When an `IObservable` is created by using an Expression e.g. `WhenValueChanged(x => x.Property)` an instance of the compiled expression is stored in `ObservablePropertyFactoryCache.Instance._factories`.

The key is generated by calling `ToCacheKey()` which uses the FullName and the Member name.

If another assembly is loaded that contains a type with the same name `ToCacheKey()` produces the same key and the lookup succeeds. This leads to the creation of an instance of the wrong type which fails on casting.

The following exception is an example:

```
Unhandled exception. System.InvalidCastException: [A]DynamicData.Binding.ObservablePropertyFactory`2[AvaloniaPreviewTest.ViewModels.OutlineItemViewModel,System.Boole
an] cannot be cast to [B]DynamicData.Binding.ObservablePropertyFactory`2[AvaloniaPreviewTest.ViewModels.OutlineItemViewModel,System.Boolean]. Type A originates from
'DynamicData, Version=6.13.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\projects\Avalonia.Preview\Avalonia.Preview\bin\Debug\n
etcoreapp5.0\DynamicData.dll'. Type B originates from 'DynamicData, Version=6.13.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\
projects\Avalonia.Preview\Avalonia.Preview\bin\Debug\netcoreapp5.0\DynamicData.dll'.
   at DynamicData.Binding.ObservablePropertyFactoryCache.GetFactory[TObject,TProperty](Expression`1 expression) in d:\a\1\s\src\DynamicData\Binding\ObservablePropert
yFactoryCache.cs:line 28
   at DynamicData.Binding.NotifyPropertyChangedEx.WhenChanged[TObject,TProperty](TObject source, Expression`1 expression, Boolean notifyInitial, Func`1 fallbackValue
) in d:\a\1\s\src\DynamicData\Binding\NotifyPropertyChangedEx.cs:line 432
   at DynamicData.Binding.NotifyPropertyChangedEx.WhenValueChanged[TObject,TProperty](TObject source, Expression`1 propertyAccessor, Boolean notifyOnInitialValue, Fu
nc`1 fallbackValue) in d:\a\1\s\src\DynamicData\Binding\NotifyPropertyChangedEx.cs:line 100
   at AvaloniaPreviewTest.Views.OutlineItemView.<>c.<.ctor>b__0_2(OutlineItemViewModel vm)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
```

## Workaround
As the class is internal and does not expose any outside mechanism to flush the cache, my current
 workaround involves flushing the cache using reflection like so before loading a new assembly:

```csharp
static void ClearCache()
{
  /* get the internal type */
  var type = Assembly.Load("DynamicData").GetTypes()
    .FirstOrDefault(t => t.FullName == "DynamicData.Binding.ObservablePropertyFactoryCache");
  
  /* get static instance */
  var instance = type.GetField("Instance").GetValue(null);
  var factoriesFieldInfo = type.GetField("_factories", BindingFlags.Instance | BindingFlags.NonPublic);

  /* get the internal dictary */
  var dictionary = (ConcurrentDictionary<string, object>) factoriesFieldInfo.GetValue(instance);
  
  /* clear the internal cache */
  dictionary.Clear();
}
```

## Questions
- Maybe improving `ToCacheKey()` to incorporate details of the assembly would solve the issue, e.g. `Assembly.FullName` or `Assembly.Location` instead of just relying on the Type name?
- On the other hand I guess it would be nice if there was an explicit way to access / clear the cache?
- Are there better alternatives for creating Observables that are not being cached in the first place?

What do you think?
Thank you!

Take care,
Martin

**Comment by RolandPheasant** [comment]
This is a brilliant example of however well you think out the code, there is a bug hidden some where!

Regarding your considerations, the observables are cached primarily to ensure that the lambda expression is only compiled once which significantly improves performance.  Therefore the first suggestion of including the assembly in the type key is my preferred option.

Longer term I think we need a complete rethink like potentially using code generation.

**Comment by 8** [comment]
Hi Roland,
thank you for your reply (and of course the wonderful library)!

I would like to add that my use case is probably not the most common, so I would not expect that many people have the same issue. :)

Take care,
Martin

**Comment by RolandPheasant** [comment]
This took far too long to remember to fix, but I've finally included the assembly name in the cache key.
