### ISSUE TITLE
Double Sort()

### ISSUE THREAD

**Issue by alex6dj** [reactivemarbles/DynamicData#435]
Hi, is there way to double sort an obsevable cache data prior bind.

Something like OrderBy and ThenBy in linq.

**Comment by RolandPheasant** [comment]
You can. The sort method accepts a comparer and Dynamic Data has SortExpressionComparer which does exactly that.

```cs
SortExpressionComparer<MyType>.Ascending(t => t.Prop1).ThenByAscending(t => t.Prop2)
```

**Comment by alex6dj** [comment]
Thanks for the fast response. It works perfect. Now I can have the high priority task on top without losing key order.
Thanks again.
