### ISSUE TITLE
Exception handling in subscription code

### ISSUE THREAD

**Issue by ablanchet** [reactivemarbles/DynamicData#44]
Hi Roland,

I've been playing with DynamicData for a while now and I've always been confused about the exception handling.

I read the code and its unit tests and I understand that : 
- any exception thrown while editing is caught and given back to an `onError` action if any, or rethrown. Seems fair to me.
- any exception thrown while transforming or filtering will be caught and given back to all observers connected to the SourceList/SourceCache via the `OnError` action (given when subscribing).

But I think there is some kind of an unwanted weird behavior when a **subscription code** throws.

I tried with the following test :

``` CSharp
[Test]
public void SingleSubscriberThatThrows()
{
    var s = new SourceList<int>();
    s.Connect().Subscribe(i => { throw new NotImplementedException(); });

    s.Edit(u => u.Add(1));
}
```

In this test an exception is correctly thrown when the new value is added in the SourceList, but it's handled and given back to the `OnError` action. There is here only one subscriber and he's disconnected from the inner subject in the SourceList when its subscription code throws so we're not able to see any exception here. (The subject's `OnNext` method throws, the only observer is disconnected, the exception is caught and given back to the subject in order to redispatch it to the other subscribers).

Let's try with two more subscribers :

``` CSharp
[Test]
public void MultipleSubscribersWithOneThrowing()
{
    var s = new SourceList<int>();
    s.Connect().Subscribe(i => { });
    s.Connect().Subscribe(i => { throw new NotImplementedException(); });
    s.Connect().Subscribe(i => { });

    s.Edit(u => u.Add(1));
}
```

When you run this you actually have an exception thrown because there is still two other subscribers behind the underlying subject, and the exception is re-thrown because none of these subscribers handle correctly their `OnError` actions.

Now let's try with proper `OnError` handling :

``` CSharp
[Test]
public void MultipleSubscribersHandlingErrorsWithOneThrowing()
{
    var firstSubscriberExceptionHandleCount = 0;
    var secondSubscriberExceptionHandleCount = 0;
    var s = new SourceList<int>();
    s.Connect().Subscribe(i => { }, e => firstSubscriberExceptionHandleCount++);
    s.Connect().Subscribe(i => { throw new NotImplementedException(); });
    s.Connect().Subscribe(i => { }, e => secondSubscriberExceptionHandleCount++);

    s.Edit(u => u.Add(1));

    Assert.That(firstSubscriberExceptionHandleCount, Is.EqualTo(1));
    Assert.That(secondSubscriberExceptionHandleCount, Is.EqualTo(1));
}
```

This test is successful ! The two `OnError` actions are correctly called by the underlying subject. And the exception is thus correctly handled. 

The code behind this behavior is the `InvokeNext` method on SourceList (and same on SourceCache) :

``` Csharp
private void InvokeNext(IChangeSet<T> changes)
{
    if (changes.Count == 0) return;

    lock (_locker)
    {
        try
        {
            _changes.OnNext(changes);

            if (_countChanged.IsValueCreated)
                _countChanged.Value.OnNext(_readerWriter.Count);
        }
        catch (Exception ex)
        {
            _changes.OnError(ex);
        }
    }
}
```

I understand that using the `OnError` action of a subscriber is pretty useful when handling exceptions in filters or tranformers but catching exceptions the way it's done in `InvokeNext` method is very dangerous in my opinion. 
It's _okay_ when multiple subscribers are connected to the observable because the exception will be given to them or thrown by the underlying subject when the `OnError` action is not given to all subscribers ... there is a way to be notified of the exception (it's just _okay_ for me because this way feels a bit weird :smile: )

But it's very dangerous when only one subscriber is connected : the exception will be swallowed and the subscription will remain _broken_ due to the behavior of the underlying subject. No changes will be propagated after that.

And finally it's _mega dangerous_ when using the DynamicData's `RefCount` operator because it wraps the underlying observer and give an empty implementation to the `OnError` action that swallows the exception.

My last test was using the RefCount operator:

``` CSharp
[Test]
public void ExceptionShouldBeThrownInSubscriberCode()
{
    var changesCountFromSubscriber1 = 0;
    var changesCountFromSubscriber2 = 0;
    var source = new SourceList<int>();

    var observable = source.Connect().RefCount();
    observable.Subscribe(i => changesCountFromSubscriber1++);
    observable.Subscribe(i => { throw new NotImplementedException(); });
    observable.Subscribe(i => changesCountFromSubscriber2++);

    source.Edit(l => l.Add(1));
    source.Edit(l => l.Add(2));

    Assert.That(changesCountFromSubscriber1, Is.EqualTo(2));
    Assert.That(changesCountFromSubscriber2, Is.EqualTo(2));
}
```

The result is scary : 
- no exception thrown anywhere
- `changesCountFromSubscriber1` equals 1 instead of 2. 
- `changesCountFromSubscriber2` equals 0 instead of 2.
- all the changes after that will be ignored

The first `Add` works and then the exception is thrown, the second subscriber is not called, the subject is completed and the following calls are just dropped. You have to unsubscribe and subscribe again to make it work.

Sorry for the super long issue but I think it can be a tricky bug to find for the users of this library (I am one, and I had this bug once :smile:  )
I really don't have any good idea to solve this at the moment but I'm sure we can find something great :+1: 

Any thoughts ?

**Comment by ablanchet** [comment]
I've just pushed a few new tests that show how I was expecting the error handling behavior on my fork : https://github.com/ablanchet/DynamicData/commit/76077f442c115bf309256b0f4dce2c1e5f8599a7

**Comment by RolandPheasant** [comment]
@ablanchet that is not too long an explanation. It is in fact a very difficult area to consistently and logically deal with.  When and how to handle and to propagate errors is something which I have always felt I should pay more attention to but I have never felt the pressing need.  Additionally the lack of handling in RefCount() is perhaps sloppy!  [that operator was quickly cobbled together to assist in handling a very intensive memory issue on a specific system].

How about we collaborate and get this one right once and for all. If an API change is required it could always become dynamic data v5? What do you think?

**Comment by ablanchet** [comment]
@RolandPheasant yes I'd be very to help getting this done once for all !

The error handling is indeed a difficult thing to deal with, especially in Rx I think. For me two solutions are possible : 

1. being super safe, catching every exception whenever it's possible and give it back to user code using a trick (another observable of exceptions ?)
2. being not safe at all and let the user deal with its own error handling.

Personally I think we should stay as close as possible to the _native_ Rx's behavior : ie. don't handle the exceptions and try to give it back to user code. Let exceptions be thrown even if it's while editing/filtering/transforming/subscribing. This is why I'd prefer the second solution exposed.

But I may miss something here ... Why did you add this error handling feature in the first place ?

And yes, I think it's a good idea to target a v5, it will leave us the freedom to break things in the API :smile: . Do you already have a v5 roadmap in mind ?
