### ISSUE TITLE
How to create a ISourceList with select a property?

### ISSUE THREAD

**Issue by sericaer** [reactivemarbles/DynamicData#441]
I want to observe a property which is in the elem in SourceList. 
When the SourceList add elem or the property is changed, the property list is observed.

For example:

           //Test is implement with INotifyPropertyChanged
            SourceList<Test> list = new SourceList<Test>();

            list.Connect()
                .HowToSelectPropertyAsSourceList(x => x.property) //How to select property as ISourceList?
                .Subscribe(x =>
                {
                    Console.WriteLine(String.Join(",", x));
                });

            //Console.WriteLine: 0
            var test0 = new Test(0);
            list.Add(test0); 

            //Console.WriteLine: 0,1
            var test1 = new Test(1);
            list.Add(test1);

            //Console.WriteLine: 0,10
            test1.property = 10;

Thanks alot!

**Comment by glennawatson** [comment]
Try the Transform() operator, it's the equilavent of the Linq Select statement

There's also TransformAsync()

**Comment by sericaer** [comment]
used Transform(), I can observe "list.Add", but not observe "test1.property = 10"

**Comment by glennawatson** [comment]
https://github.com/reactivemarbles/DynamicData#observing-properties-of-objects-in-a-collection

**Comment by sericaer** [comment]
Thanks，but I want observe all elem's  property as CombineLast.

**Comment by glennawatson** [comment]
We usually reserve issues for bugs or feature requests. Feel free to join on slack and ask your question. You can join slack at https://www.reactiveui.net/slack and join channel #dynamicdata to ask.
