### ISSUE TITLE
Deadlock when subscribing to SourceCache to which item is added

### ISSUE THREAD

**Issue by ShadowDancer** [reactivemarbles/DynamicData#442]
`using DynamicData; (6.17.14)`

Steps to reproduce:
1. Create `SourceCache` and add handler to it (for instance `OnItemAdded`)
2. In handler connect and subscribe to `SourceCache` on new thread
3. Add item to `SourceCache`

Expected results:
Everything returns and contents of both SourceCaches are synchronized

Actual results:
Deadlock

I am not sure if this is bug, or unsupported by design.
The problem arises, when in reaction to adding item to `SourceCache` another thread tries to subscribe to this `SourceCache`.
In my app this happens because in reaction to item being added to initial cache (which is source of truth for entire system) other components are spawned and try to  subscribe to this cache. 

I see two possible outcomes:
1. Subscribe does nothing, AddOrUpdate returns and then notification with new item is generated
2. Current contents of source cache are returned, and then `AddOrUpdate` returns and notification is 

This works on single thread because of reentrant locks.

Repro source code:
```
using System;
using System.Threading.Tasks;
using DynamicData;
 
namespace DynamicDataDeadlock
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Started!");
 
            var cache = new SourceCache<string, string>(o => o);
            cache.Connect().OnItemAdded(n =>
                Task.Run(() => { cache.Connect().Subscribe(); }).GetAwaiter().GetResult());
 
            cache.AddOrUpdate("x");
 
            Console.WriteLine("Finished");
        }
    }
}
```

**Comment by MihailsKuzmins** [comment]
Does the deadlock occur if you use "async\await" instead of GetAwaiter().GetResult(), i.e.
```cs
using System.Reactive.Linq;

Task.Run(async () => await cache.Connect())
```

from my personal experience "GetAwaiter().GetResult()" is more likely to cause a deadlock than "async/await"

**Comment by RolandPheasant** [comment]
Dynamic data is not immune to re-entrancy locking.  In order to synchronize any inflight notifications the source musts be locked, otherwise the rx contract of only one notification in flight would be broken and all hell would break loose.

I suggested re-thinking re-subscription as a side effect.
