### ISSUE TITLE
[Question] SourceCache<T> - auto refresh doesn't work

### ISSUE THREAD

**Issue by SignumPL** [reactivemarbles/DynamicData#453]
I have SourceCache populated with some data. I need to filter this data based on the category selected by the user. I tried to use AutoRefreshOnObservable and pass Subject<Unit> to trigger refresh, however it doesn't work (auto refresh is not triggering and output collection doesn't change):

```cs
enum Category
{
    Even,
    Odd
}

class MyDto
{
    public int Number { get; set; }
    public Category Category { get; set; }
}

[Fact]
public void Test()
{
    ReadOnlyObservableCollection<MyDto> filteredDtos;

    SourceCache<MyDto, int> source = new SourceCache<MyDto, int>(x => x.Number);
    source.AddOrUpdate(Enumerable.Range(1, 10).Select(x => new MyDto()
    {
        Number = x,
        Category = x % 2 == 0 ? Category.Even : Category.Odd
    }));

    Category selectedCategory = Category.Even;
    Subject<Unit> refresh = new Subject<Unit>();

    source.Connect()
        .AutoRefreshOnObservable(_ => refresh)
        .Filter(x => x.Category == selectedCategory)
        .Bind(out filteredDtos)
        .Subscribe();

    // Act & Assert

    filteredDtos.All(x => x.Number % 2 == 0).Should().BeTrue(); // this is ok

    // Change category and trigger refresh
    selectedCategory = Category.Odd;
    refresh.Next();

    filteredDtos.All(x => x.Number % 2 == 0).Should().BeFalse(); // assertion fails
}
```

What am I doing wrong and how to fix it?

**Comment by atlemann** [comment]
Not entirely sure, but should you call `refresh.OnNext()` and not `refresh.Next()`?

**Comment by owoudenberg** [comment]
I've executed your test using DynamicData 7.1.1 and modifying the refresh.Next() to refresh.OnNext(Unit.Default) and then the test succeeds.

**Comment by SignumPL** [comment]
Yeah that makes sense, stupid mistake :)
But in the meantime I discovered that `source.Refresh()` also works and has WAY better performance.
