### ISSUE TITLE
Question on joining keys

### ISSUE THREAD

**Issue by agnauck** [reactivemarbles/DynamicData#456]
Is it possible when using the SQL like Join functions to provide a join key on both sides? left and right side?

Eg when I am using **LeftJoin** for example it always joins on the key of the left SourceCache. I can only provide the key of the right side.
I have use cases where I want to join on other required (not null) properties of the left side.
Or should I use something different than LeftJoin?

Thanks

**Comment by RolandPheasant** [comment]
Thinking about this, you can solve the problem using the 'ChangrKey'  operator on the left side before joining.
