### ISSUE TITLE
Add async support for TransformMany

### ISSUE THREAD

**Issue by JunkyXL86** [reactivemarbles/DynamicData#461]
There is an async version TransformAsync() accepting a Task<T> as return value.
Similarly there should be an async version for TransformMany() to achieve the same with collections.

Is there an actual workaround to get this working?

**Comment by RolandPheasant** [comment]
Ideally, this should be implemented

**Comment by RolandPheasant** [comment]
Closed by the mentioned PR

**Comment by dwcullop** [comment]
Sorry but that PR does not address this.  I was just being too chatty and mentioned what other issues I was considering addressing.  My apologies.

**Comment by dwcullop** [comment]
`TransformManyAsync` and `TransformManySafeAsync` where implemented by #824.
