### ISSUE TITLE
NULL is not considered to be a valid value in Optional<T>

### ISSUE THREAD

**Issue by MihailsKuzmins** [reactivemarbles/DynamicData#463]
I have a question about the null check in the constructor of Optional<T>, i.e. if a value is null it is considered that the Optional has no value, but I would expect that null is still a valid value.
https://github.com/reactivemarbles/DynamicData/blob/main/src/DynamicData/Kernel/Optional.cs#L29

I may be wrong, but isn't it a concept of the optional value that it could have three possible values as listed below?
1. not null - HasValue is true
2. null - HasValue is true
3. no value - HasValue is false

**Comment by RolandPheasant** [comment]
I designed, and then consumed throughout the code base to assume null is not a valid value. Probably a bit risking an involved to change
