### ISSUE TITLE
[BUG] when SubscribeOn a collection ,we cannot receive any notification

### ISSUE THREAD

**Issue by Luoyingliang** [reactivemarbles/DynamicData#465]
I want to observe a collection changed and process the notification in another thread,but when i call SubscribeOn method,it doesn't work, when i remove the SubscribeOn method it work so well.

Environment:
SDK : .Net 5.0 SDK
LIB: ReactiveUI 13.0.1
ReactiveUI.WPF 13.0.1
System.Reactive 5.0.0
OS: Windows 10

 public class Model
 {
     public string Text { get; set; }
 }
 /// <summary>
 /// Interaction logic for MainWindow.xaml
 /// </summary>
 public partial class MainWindow : Window
 {
     private ObservableCollectionExtended<Model> Collection;

     public MainWindow()
     {
         InitializeComponent();

         //
         // it test can subscribeOn method work on thread pool scheduler
         Collection = new ObservableCollectionExtended<Model>();
         Collection.WhenAnyPropertyChanged()
                   .SubscribeOn(RxApp.TaskpoolScheduler)
                   .Select(x => x!)
                   .Subscribe(x =>RxApp.TaskpoolScheduler.Schedule(()=> Debug.WriteLine($"collection work on thread:{Thread.CurrentThread.ManagedThreadId}")));
         Collection.Add(new Model());
     }
 }

**Comment by glennawatson** [comment]
From @RolandPheasant 

> This is not a dynamic data issue. An observable collection cannot be touched by a non UI thread.

Closing this.

Consider maybe using a `SourceList<T>` instead with a `Bind(out )` to a `ReadOnlyObservableCollection`. SourceList has observables you can potentially sign up to that notify you of property changes also.
