### ISSUE TITLE
Add information regarding populate methods in ObservableCacheEx

### ISSUE THREAD

**Issue by Awsmolak** [reactivemarbles/DynamicData#470]
Granted I am fairly new to ReactiveEx and DynamicData but I had a use case which was easily solved using the PopulateInto extension method. It cost me a decent amount of time until I read through the source. I think maybe the wiki or readme.md could benefit from a quick mention of ObservableCacheEx.PopulateFrom and ObservableCacheEx.PopulateInto.

**Comment by RolandPheasant** [comment]
Feel free to add a wiki page on the topic. It would be much appreciated.

**Comment by Awsmolak** [comment]
Added a page to the wiki: [Chaining collections using Populate extension methods](https://github.com/reactivemarbles/DynamicData/wiki/Chaining-collections-using-Populate-extension-methods)

Let me know if it seems to be a clear explanation...or if I have anything confused!
