### ISSUE TITLE
Connect predicate is filtering out changes and not updating bound lists correctly

### ISSUE THREAD

**Issue by davecader** [reactivemarbles/DynamicData#471]
We are using an instance of SourceCache to which we are connecting multiple times, which each Connect call using a different predicate to differentiate items and bind them to instances of ReadOnlyObservableCache. With the latest version we are observing a change in behavior in the way changes are propagated when predicates are used to connect to a SourceCache.

Specifically,  an update to an item in the cache that should cause the item to move from one bound collection to another, due to the connection predicates that were specified, does not remove the item from the collection where it should no longer exist. In other words, it appears in both collections, even though the connection predicate should be excluding it from one of them.  

It would seem that the Connect method predicate is filtering out the changes and as a result the item remains in the collection where it should no longer exist. I am not sure exactly when this change in behavior started, but it was working as expected with 16.14.3 and earlier versions of DynamicData.

Also, it appears that the expected behavior can be obtained by moving the predicates to Filter calls and using parameter-less Connect calls. So this issue appears to affect only Connect and not static Filter operations.

**Comment by davecader** [comment]
This issue also seem to be affecting the how remove changes are being propagated to bound collections.

**Comment by davecader** [comment]
Sorry, it looks like this is a duplicate of issue #400.

**Comment by AlBannaTechno** [comment]
> 
> 
> Sorry, it looks like this is a duplicate of issue #400.

I think it is not, I still have this issue

### Remove any item, does not propagate changes to the system

and I work around it with
```C#

// private readonly SourceCache<Address, Guid> _addressesSource
// [Reactive] public ObservableCollectionExtended<SelectableCountedItem<Address>> Addresses { get; set; }
// 

SelectableCountedItem<Address> AddressCast(Address address) => 
                new SelectableCountedItem<Address>(address, 
                    // we must keep this, because after adding new address
                    selected: ExternalAddresses.Any(a => a.Id == address.Id));

 _addressesSource
                .Connect()
                .Sort(new AddressesSortAc())
                .Cast(AddressCast)
                .ObserveOnDispatcher()
                .Bind(Addresses)
                .Subscribe(changes =>
                {
		   // ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    foreach (var change in changes)
                    {
                        if (change.Reason != ChangeReason.Remove) continue;
                        var toRemove = Addresses.FirstOrDefault(a => a.Content.Id == change.Key);
                        if (toRemove == null) continue;
                        Addresses.Remove(toRemove);
                    }
                });
```

**Comment by RolandPheasant** [comment]
This has been fixed as part of some prior change - I raise the PR above with a unit test to illustrate.
