### ISSUE TITLE
[Regression] Exception when using .Sort with comparerChanged overload and AddRange

### ISSUE THREAD

**Issue by bruzkovsky** [reactivemarbles/DynamicData#473]
After upgrading from DynamicData 6.x to 7.x, my ListViews (Xamarin.Forms) were suddenly empty. Fortunately there was an Exception thrown and with that information I could narrow the problem down to the following:

![image](https://user-images.githubusercontent.com/10390959/117660239-3ad5bd00-b19d-11eb-86ab-95a6c195ed95.png)

When using `.Sort(IObservable<IComparer<T>> comparerChanged)`, then an initial `.AddRange` will basically be ignored, unless `observerChanged` ticked at least one value or `T` implements `IComparable`.

You can repro this with the following small example: 
[ReproDynamicDataSort.zip](https://github.com/reactivemarbles/DynamicData/files/6452085/ReproDynamicDataSort.zip)

```cs
var source = new SourceList<ListItem>();
var sorter = new Subject<IComparer<ListItem>>();

source.Connect()
    .Sort(sorter)
    .Bind(out var bound)
    .Subscribe();

source.AddRange(Enumerable.Range(1, 10).Select(i => new ListItem(i)));
sorter.OnNext(SortExpressionComparer<ListItem>.Descending(x => x.Number));
```

The sample is really simple, it creates a `SourceList`, passes the sorter and then adds 10 items. The key part is that the sorter *does not tick before the items are added*, e.g. switching the last 2 lines will make the code work. Unfortunately, I have cases where I do not know the order beforehand, so I cannot do something like this in my production code.

It seems that since DynamicData 7.x, the internal comparer is initialized with `Comparer<T>.Default`, which needs the items to implement `IComparable`. Whereas in DynamicData 6.x, there was a fallback for when there is no comparer available. From my point of view, it should be sufficient to implement that fallback again.

**Comment by RolandPheasant** [comment]
Thanks for the reproduction.

The reason for the error is timing. Within the sort code, the changes are subscribed to before the comparer changed stream, which means that the code tries to sort using the default object comparer which expects the object to implement IComparable.

A simple solution around this would be to implement `IComparable`:

```cs
    internal class ListItem: IComparable<ListItem>
    {
        public static readonly IComparer<ListItem> DefaultComparer = SortExpressionComparer<ListItem>.Ascending(x => x.Number);

        public int Number { get; }

        public ListItem(int number)
        {
            Number = number;
        }

        public int CompareTo(ListItem other) => DefaultComparer.Compare(this, other);
    }
```

The fix within Dynamic Data will be to subscribe to the comparer changes before subscribing to item changes. I'll try this out and if it works will merge it.

**Comment by RolandPheasant** [comment]
Doh, I did the investigation after reading the first comment. Now I have scrolled down and seen that you had worked out the same.   In case you did not know the "pseduo-comparer" method is exactly what all primitives implement. That's why for the error would not occur if you are sorting build in structures.

What I am still unsure of is why the error only occurs for you after an upgrade,

**Comment by bruzkovsky** [comment]
> the "pseduo-comparer" method is exactly what all primitives implement

Interesting, I didn't know that! I'll try implementing `IComparable` then.

It looks like this line is the culprit: [src/DynamicData/List/Internal/Sort.cs#L34](https://github.com/reactivemarbles/DynamicData/blame/36d18e0f34457d4682fea1d68e2e65e8800f87fc/src/DynamicData/List/Internal/Sort.cs#L34)

Also, this seems to be only regarding List, not Cache: [src/DynamicData/Cache/Internal/Sort.cs](https://github.com/reactivemarbles/DynamicData/blame/ec02c3b84d6272b812c3ad5c21b2ee30ce8b41e7/src/DynamicData/Cache/Internal/Sort.cs)
