### ISSUE TITLE
Ignoring sort if SortExpressionComparer null

### ISSUE THREAD

**Issue by Awsmolak** [reactivemarbles/DynamicData#498]
If you use sort on a cache with a null observable comparer, the order of items appears to be random. I assume -1 or some default value is getting applied to the items for sorting in those cases.

Feature request:
It seems to me like it would make more sense (and helpful in my particular use case!) that the sort would be completely ignored if null were passed for the comparer. Then items would be enumerated in the order in which they received as if sort had not been used.

OR

I assumed that this wouldn't be possible...But if there were a way to construct a comparer that preserved source ordering, that would suffice as well.

I realize that I could probably switch stream subscriptions by observing the comparer and checking for null. But that seems like quite a bit of added complexity.

**Comment by Awsmolak** [comment]
This SO issue clarified some things for me:
https://stackoverflow.com/questions/60631690/strange-dynamicdata-sorting
Maybe some clarification in the wiki sorting section would help. I can PR something there.

**Comment by RolandPheasant** [comment]
A PR will be welcomed.

**Comment by Awsmolak** [comment]
I just edited the wiki directly:
https://github.com/reactivemarbles/DynamicData/wiki/Sorting/_compare/a5fd1cdfffc7e6c31c766d962f5f6e83534398e6
