### ISSUE TITLE
ToObservableChangeSet always append to the end of ChangeAwareList

### ISSUE THREAD

**Issue by lucasnmilagres** [reactivemarbles/DynamicData#507]
When using a BindingList as a source, even if you insert a new item in an specific index, the ChangeAwareList (named "list") used inside the BindingListEx.ToObservableChangeSet will have the new item appended on its last position. It's caused because of the logic inside this case statement:

```
case ListChangedType.ItemAdded when source[changes.NewIndex] is T newItem:
{
         list.Add(newItem);
         break;
}
```

I would like to ask the community about the potential impacts of changing the list.Add for list.Insert and propose it as a change in the future.

Supposing this code snippet:

```
var bindingList = new BindingList<string>() {"a", "b", "c", "d"};
bindingList.ToObservableChangeSet()
        .Bind(TargetObservableCollection)
        .Subscribe()
        .DisposeWith(BindingListDisposable)

bindingList.Insert(2, "Z at index 2");
TargetObservableCollection.ForEach(x => Console.WriteLine(x));
```

The current implementation outputs:
```
"a"
"b"
"c"
"d"
"Z at index 2"
```

While the expected (which can be achieved with the replacement of list.Add for list.Insert) is:
```
"a"
"b"
"Z at index 2"
"c"
"d"
```

**Comment by RolandPheasant** [comment]
Sorry for the delay on this, and thanks for the exact analysis and reproduction
