### ISSUE TITLE
SourceList implement ICollection

### ISSUE THREAD

**Issue by RomanSoloweow** [reactivemarbles/DynamicData#534]
If SourceList inherits from ICollection, this allows it to be used in more flexible architectures.

Now it is impossible to use SourceList when inheriting an interface in which ICollection is specified (add method is needed)

**Comment by RomanSoloweow** [comment]
SourceList + SourceListEditConvenienceEx already contains all the methods necessary for the implementation of ICollection (except CopyTo)
![image](https://user-images.githubusercontent.com/29205560/143149257-d49b87db-8645-421f-a33f-3611c3faa52a.png)

**Comment by glennawatson** [comment]
This is as designed. Don't believe anyone wants this change since it's a private internal class, and its intended to make it obvious to the user it's not designed to used as a pure list.
