### ISSUE TITLE
[BUG] Thread safety in ObservableCache.Connect (regression)

### ISSUE THREAD

**Issue by pmg23** [reactivemarbles/DynamicData#538]
The thread safety of `ObservableCache.Connect` (previously fixed in #377) is broken again by #472.

It is imperative to hold the lock on `_locker` while fetching the initial changeset and subscribing to changes. Otherwise any changes made from another thread between the point when, for a new subscription, `InternalEx.Return` computes the initial state, and later the `Concat` impl subscribes to `_changes`, will be lost.

https://github.com/reactivemarbles/DynamicData/blob/811b32eacff481f0968545cadc33cca0e6cfd6de/src/DynamicData/Cache/ObservableCache.cs#L106-L131

(Observed in 7.4.3, but should affect 7.1.16 onwards.)

**Comment by RolandPheasant** [comment]
Hopefully the PR will fix it.

**Comment by pmg23** [comment]
Looks good. Thanks for the fast turnaround.
