### ISSUE TITLE
Virtualise and Page cause exception on non-unique list

### ISSUE THREAD

**Issue by navozenko** [reactivemarbles/DynamicData#540]
Virtualise and Page methods cause ArgumentOutOfRangeException if the list contains equal elements. Is it by design or a bug?

```csharp
var source = new SourceList<string>();
source.AddRange(Enumerable.Repeat("item", 10));
source.Connect()
    .Virtualise(new BehaviorSubject<IVirtualRequest>(new VirtualRequest(0, 3)))
    .Subscribe();
```
or

```csharp
var source = new SourceList<string>();
source.AddRange(Enumerable.Repeat("item", 10));
source.Connect()
    .Page(new BehaviorSubject<IPageRequest>(new PageRequest(0, 3)))
    .Subscribe();
```

Tested on version 7.4.9

**Comment by navozenko** [comment]
The exception seems to occur because Virtualise and Page use LINQ Except method to detect added and deleted items.

```csharp
var adds = current.Except(previous);
var removes = previous.Except(current);
```
This approach works fine when all items in the list are unique, but fails when there are equal items.

**Comment by RolandPheasant** [comment]
Out of interest, is there an obvious and easy alternative to using linq?
