### ISSUE TITLE
ObservableListEx.Cast throws sometimes a System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by gsgou** [reactivemarbles/DynamicData#574]
STACKTRACE:

(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
DynamicData
ObservableListEx+<>c__20`1[TDestination].<Cast>b__20_1 (System.Object t)
DynamicData
ChangeSetEx+<>c__DisplayClass2_0`2[TSource,TDestination].<Transform>b__0 (DynamicData.Change`1[T] change)
System.Linq
Enumerable+SelectListIterator`2[TSource,TResult].MoveNext ()
System.Collections.Generic
List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable)
System.Collections.Generic.List`1[T]
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <32a51bdb16cb4c7cb54d063a65fedc73>:0
DynamicData.ChangeSet`1[T]
DynamicData.ChangeSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] items) [0x00000] in <beba8b19d1e742dba8c4a0c65cc77f58>:0
DynamicData
ChangeSetEx.Transform[TSource,TDestination] (DynamicData.IChangeSet`1[TObject] source, System.Func`2[T,TResult] transformer)
DynamicData
ObservableListEx+<>c__20`1[TDestination].<Cast>b__20_0 (DynamicData.IChangeSet`1[TObject] changes)
System.Reactive.Linq.ObservableImpl
Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
System.Reactive.PlatformServices
ExceptionServicesImpl.Rethrow (System.Exception exception)
System.Reactive
ExceptionHelpers.Throw (System.Exception exception)
System.Reactive.Stubs+<>c
<.cctor>b__2_1 (System.Exception ex)
System.Reactive
AnonymousSafeObserver`1[T].OnError (System.Exception error)
System.Reactive
Sink`1[TTarget].ForwardOnError (System.Exception error)
System.Reactive.Linq.ObservableImpl
Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
System.Reactive
AutoDetachObserver`1[T].OnNextCore (T value)
System.Reactive
ObserverBase`1[T].OnNext (T value)
System.Reactive
Sink`1[TTarget].ForwardOnNext (TTarget value)
System.Reactive.Linq.ObservableImpl
Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
System.Reactive
Sink`1[TTarget].ForwardOnNext (TTarget value)
System.Reactive.Linq.ObservableImpl
Scan`2+_[TSource,TAccumulate].OnNext (TSource value)
System.Reactive.Subjects
Subject`1[T].OnNext (T value)
System.Reactive.Linq.ObservableImpl
FromEventPattern+Impl`2+<>c__DisplayClass3_0[TDelegate,TEventArgs].<GetHandler>b__1 (System.Object sender, TEventArgs eventArgs)
(wrapper delegate-invoke) <Module>.invoke_void_object_NotifyCollectionChangedEventArgs(object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)
System.Collections.ObjectModel
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
System.Collections.ObjectModel
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index)
System.Collections.ObjectModel
ObservableCollection`1[T].InsertItem (System.Int32 index, T item)
XYZ.Helpers
ObservableUniqueCollection`1[T].InsertItem (System.Int32 index, T item)
System.Collections.ObjectModel
Collection`1[T].Add (T item)
Xamarin.Forms
SelectionList.Add (System.Object item)
Xamarin.Forms.Platform.Android
SelectableItemsViewAdapter`2[TItemsView,TItemsSource].UpdateFormsSelection (System.Int32 adapterPosition)
Xamarin.Forms.Platform.Android
SelectableItemsViewAdapter`2[TItemsView,TItemsSource].SelectableClicked (System.Object sender, System.Int32 adapterPosition)
Xamarin.Forms.Platform.Android
SelectableViewHolder.OnViewHolderClicked (System.Int32 adapterPosition)
Xamarin.Forms.Platform.Android
SelectableViewHolder.OnClick (Android.Views.View view)
Android.Views
View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.59(intptr,intptr,intptr)

Seen few times in Android 8.1, or 11. Could relate on Xamarin.Forms or ReactiveUI binding too.
SelectedModels is bound to a CollectionView's SelectedItems 

            SelectedModels = new ObservableUniqueCollection<object>();
            SelectedModels.AddRange(_orderedModels.Where(l => l.IsSelected == true));
            SelectedModels
                .ToObservableChangeSet()
                .Cast<SomeModel>()
                .Catch((InvalidCastException ex) =>  Observable.Empty<IChangeSet<SomeModel>>())
                .ToCollection()
                .Buffer(2, 1)
                .Select(b => new { PreviousSelection = b[0], CurrentSelection = b[1] })
                .Subscribe(b =>
                    {
                        // some logic
                    };
I do not see any relation on https://github.com/reactivemarbles/DynamicData/issues/434
Any ideas why such a cast fails? I see that ObservableListEx.Cast checks for nulls.

**Comment by RolandPheasant** [comment]
Is there any way to replicate within a unit test?

**Comment by RolandPheasant** [comment]
Could it be that the platform is adding some objects to the collection view which are intended for internal use only.  I cannot remember the details but I have seen such things in WPF, which is one reason why I never use a CollectionView and instead rely on ItemsSource binding.

If this can be replicated in a unit test please reopen and I'll investigate further, otherwise I will assume it's platform related.

The only null checks in `ObservableListEx.Cast` are collection null checks and the cast does no checking.
