### ISSUE TITLE
[Bug]: OnItemRemoved must not execute.

### ISSUE THREAD

**Issue by a44281071** [reactivemarbles/DynamicData#613]
### Describe the bug 🐞

``` csharp
            var source = new SourceCache<Person, int>(x => x.Age);
            source.Connect()
                //.Bind(person_items)
                .OnItemAdded(_ => Trace.TraceInformation("OnItemAdded()"))

                // He must not trace
                .OnItemRemoved(_ => Trace.TraceInformation("OnItemRemoved(). But this is error message."))
                // He must not trace

                .OnItemUpdated((_, _) => Trace.TraceInformation("OnItemUpdated()"))
                .ForEachChange(change =>
                {
                    Trace.TraceInformation("Changed({0}) old = {1}, new = {2}", change.Reason, change.Previous, change.Current);
                })
                .Subscribe();

            var person = new Person("A", 1);
            //var person2 = new Person("A", 1);
            source.AddOrUpdate(person);
            source.AddOrUpdate(person);
```

### Reproduction repository

https://github.com/reactivemarbles/DynamicData

### Expected behavior

TestDynamicData Information: 0 : OnItemAdded()
TestDynamicData Information: 0 : Changed(Add) old = <None>, new = A. 1
TestDynamicData Information: 0 : OnItemUpdated()
TestDynamicData Information: 0 : Changed(Update) old = A. 1, new = A. 1

### Screenshots 🖼️

TestDynamicData Information: 0 : OnItemAdded()
TestDynamicData Information: 0 : Changed(Add) old = <None>, new = A. 1
TestDynamicData Information: 0 : OnItemRemoved(). But this is error message.
TestDynamicData Information: 0 : OnItemUpdated()
TestDynamicData Information: 0 : Changed(Update) old = A. 1, new = A. 1

### IDE

Visual Studio 2022

### DynamicData Version

7.9.1

### Additional information ℹ️

[_No response_](https://github.com/a44281071/TestDynamicData/blob/1d5759b251c9b1c2f94a4d62378c4f1a37db59bb/TestDynamicData/Test/TestOnItemRemovedCalled.cs#L27)

**Comment by RolandPheasant** [comment]
You're right. This comes from shared code with `DisposeMany` which treats the previous item as having been removed.

I'll fix it soon.
