### ISSUE TITLE
[Bug]: Index out of range exception on transform multiple subscribes

### ISSUE THREAD

**Issue by LouisSimon73** [reactivemarbles/DynamicData#618]
### Describe the bug 🐞

When we store tranformed changeSet stream in variable and subscribe multiple time on this variable, on exception occures on the second subscription.

-  We did not have the problem in 7.4.3;
-  It does not happen with connectable observable ([variable].Publish().RefCount()).

Thank you in advance !

### Step to reproduce

```
var l_sourceList = new SourceList<int>();

l_sourceList.AddRange(new[] { 0, 1, 2 });

var l_observable = l_sourceList.Connect()
    .Transform(o => o);

l_observable.Transform(o => o).Subscribe();
l_observable.Transform(o => o).Subscribe();
```

### Reproduction repository

https://github.com/reactivemarbles/DynamicData

### Expected behavior

This should happen...

### IDE

Rider Windows

### Operating system

Windows 10 Entreprise

### Version

20H2 (19042.1645)

### Device

PC

### DynamicData Version

7.9.5

**Comment by RolandPheasant** [comment]
I had the same issue a while back with Cache.Transform and thought I'd fixed it here too, so thanks for pointing this out.

Interestingly, your observation that `.Publish().RefCount() `fixes it is what I would always recommend with any shared state as it's much more efficient.

**Comment by oysteinkrog** [comment]
@RolandPheasant We are seeing a very similar bug in TransformAsync, I will create an issue
