### ISSUE TITLE
[Feature]: TransformOnRefresh parameter for TransformAsync()

### ISSUE THREAD

**Issue by oysteinkrog** [reactivemarbles/DynamicData#620]
### Describe the functionality desired 🐞

The Transform() method has a transformOnRefresh parameter that is very handy.
It would be nice to have the same parameter available for TransformAsync()

### The steps the functionality will provide

You can call TransformAsync(.., transformOnRefresh: true).
My scenario is that I am using FilterOnObservable(..).TransformAsync(), and I want the transform to be re-applied when the filtered items change.

### Considerations

I have created a RewriteRefreshToAddRemove() extension method, but it is not as elegant as simply having the transformOnRefresh parameter.

**Comment by glennawatson** [comment]
Mind providing a comment to your RewriteRefreshToAddRemove() extension method code to assist?

**Comment by oysteinkrog** [comment]
Fixed by #625
