### ISSUE TITLE
[Feature]: Combinator for IObservableCache (similar to what exists for IObservableList)

### ISSUE THREAD

**Issue by hutterm** [reactivemarbles/DynamicData#652]
### Describe the functionality desired 🐞

in the library, currently there exists overloads for `Or` like:
`public static IObservable<IChangeSet<TObject, TKey>> Or<TObject, TKey>(this IObservableList<ISourceCache<TObject, TKey>> sources)
`
There should be something similar for IObservableCache, so that you can go easily from outer IObservableCaches of inner IObservableCaches to dynamic combinators.

Simplified, I was trying to dynamically combine inner SourceCaches of an outer SourceCache and found no other way than to go through something like this:
```
outerCache.Connect()
  .Transform(outerItem=> outerItem.InnerCache.Connect())
  .RemoveKey()
  .AsObservableList()
  .Or()
```

### The steps the functionality will provide

...

### Considerations

see above

**Comment by dwcullop** [comment]
I believe that `Or` works on SourceCache changesets.  However, if you want to flatten child/nested SourceCaches from a Parent SourceCache, you should consider the new [`MergeManyChangeSets`](https://github.com/reactivemarbles/DynamicData/pull/736) operator.

```csharp
class Inner
{
    public int Id { get; }
    public string Info { get; }
}

class Outer
{
    public int Id { get; }
    public IObservableCache<Inner, int> Nested { get; }
}

var source = new SourceCache<Outer, int>(o => o.Id);

// Populate Cache Here

// Create a merged version of all the Nested caches
var mergedNested = source.Connect().MergeManyChangeSets(outer => outer.Nested.Connect())
                                   .AsObservableChangeSet();
```

As Outer instances are added/removed from `source` any items in their Nested cache will be added to/removed from `mergedNested`.  Any items added to/removed from a nested cache, will also be reflected in `mergedNested`.

There are also overloads to that allow you to specify how to handle overlapping Keys.

**Comment by hutterm** [comment]
@dwcullop I just looked at this new operator you wrote and it actually looks like this fulfills my request. Thanks a lot!
