### ISSUE TITLE
[Bug]: Maximum / Minimum methods do not correctly handle add changes for byte and short types

### ISSUE THREAD

**Issue by kmgallahan** [reactivemarbles/DynamicData#655]
### Describe the bug 🐞

[MaxEx.cs](https://github.com/reactivemarbles/DynamicData/blob/dcfc3b483577a5ba082bb98d33be3f67b3d2757e/src/DynamicData/Aggregation/MaxEx.cs)'s Maximum and Minimum methods do not work correctly on add changes for byte & short values. 

The reason is a misunderstanding of how [IComparable.CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable.compareto) works for all numeric types. The return value is documented as:

![Screenshot 2022-10-25 105535](https://user-images.githubusercontent.com/5379488/197808359-26042627-70bf-4bde-92b7-3310f55b68cc.jpg)

Sometimes it is implemented in this way (int/uint/long/ulong/all floating-point types):

``` .cs
public int CompareTo(int value)
{
    // NOTE: Cannot use return (_value - value) as this causes a wrap
    // around in cases where _value - value > MaxValue.
    if (m_value < value) return -1;
    if (m_value > value) return 1;
    return 0;
}
```

Other times it is implemented this way (for sbyte/byte/short/ushort):

``` .cs
public int CompareTo(Int16 value) { 
    return m_value - value; 
}
```

The code currently does not work for byte & short since it only expects the return values -1/0/1:

https://github.com/reactivemarbles/DynamicData/blob/dcfc3b483577a5ba082bb98d33be3f67b3d2757e/src/DynamicData/Aggregation/MaxEx.cs#L121

@RolandPheasant @glennawatson I've submitted a PR to resolve this bug. https://github.com/reactivemarbles/DynamicData/pull/654

### Step to reproduce

See bug description.

### Reproduction repository

https://github.com/reactivemarbles/DynamicData

### Expected behavior

Maximum and Minimum should work correctly for byte & short types.

**Comment by RolandPheasant** [comment]
This is an excellent explanation, and thank you.

The funny thing is I'd always thought returning -1.0 or -1 was an odd choice for the interface! I know now that reasoning is flawed.
