### ISSUE TITLE
[Feature]: New Transform-like Query operator that is working with an IObservable-transformer

### ISSUE THREAD

**Issue by KeilFelix** [reactivemarbles/DynamicData#672]
### Background

This is a follow up feature request on #409 with a **(hopefully) new and powerful idea**. 🤞 
Every time I use DynamicData I am missing query operators that are working on IObservable like the FilterOnObservable. My TSource-objects normally have IObservable properties, and I think that this is a natural reactive design pattern.

### Idea

Basically a new query operator with the following signature _(exemplary only for ObservableList)_

`IObservable<IChangeSet<TDestination>> TransformOnObservable<TSource, TDestination>(this IObservable<IChangeSet<TSource>> source, Func<TSource, IObservable<TDestination>> transformFactory)`

#### Desired behavior
The operator should project a list where each item is the latest item from each sources' IObservable<TDestination> and should be automatically replaced if a new item is received. As long as an Observable does not provide any value there should be no entry in the list. If the Observable completes the item should be removed.

#### Possible other names

- TransformMany-overload
- TransformLatest
- TransformSwitch

#### Alternative signature

`IObservable<IChangeSet<TDestination>> TransformObservable<TDestination>(this IObservable<IChangeSet<IObservable<TDestination>>> source)`

This signature would be sufficient because a normal Transform could be done beforehand.

### Exemplary Usage
With this operator it would be easy to reimplement FilterOnObservable or a Sort/Group:

```
public static IObservable<IChangeSet<TObject>> FilterOnObservableVariant<TObject>(this IObservable<IChangeSet<TObject>> source, Func<TObject, IObservable<bool>> objectFilterObservable)
{
    return source
        .TransformOnObservable(obj => objectFilterObservable(obj).Select(filter => (Filter: filter, Object: obj)))
        .Filter(t => t.Filter)
        .Transform(t => t.Object);
}
```
_Note to above sample: Maybe a StartValue should be prepended and  a never ending Observable appended.
This would match the original behavior. But on the other side it is more natural without it and it can be easily done by the user when creating the objectFilterObservable-Func_

### Prototype Implementation
I came up with a draft and the FilterOnObservableFixture passes with this!

```
public static IObservable<IChangeSet<TDestination>> TransformOnObservable<TSource, TDestination>(
    this IObservable<IChangeSet<TSource>> source, Func<TSource, IObservable<TDestination>> transformFactory)
{
    return source.Transform(transformFactory).TransformObservable();
}

private class ObservableObjectSelector<TObject>
{
    public IObservable<TObject>? Observable { get; set; }

    public Optional<TObject> Placeholder { get; set; }
}

public static IObservable<IChangeSet<TObject>> TransformObservable<TObject>(this IObservable<IChangeSet<IObservable<TObject>>> source)
{
    if (source is null) throw new ArgumentNullException(nameof(source));

    return source
        .Transform(obs => new ObservableObjectSelector<TObject> { Observable = obs, Placeholder = Optional<TObject>.None })
        .SubscribeMany(t =>
            t.Observable.Subscribe(
                obj => t.Placeholder = Optional<TObject>.ToOptional(obj),
                () => t.Placeholder = Optional<TObject>.None))
        .AutoRefreshOnObservable(t => t.Observable)
        .Filter(t => t.Placeholder.HasValue)
        .Transform(t => t.Placeholder.Value);
}
```

### Use Cases

There are so many general use cases. I don't think it is necessary to provide an example.

### Post scriptum 
Maybe I am missing some fundamental knowledge/technique that would make it easy to achieve the desired behavior on another way. These doubts arose on me because of the statement that FilterOnObservable should be marked obsolete and that its functionality can be achieved by other means (see #409 @RolandPheasant) I kindly request an example for this or a workaround to achieve my desired behavior.

### The steps the functionality will provide

-

### Considerations

-

**Comment by KeilFelix** [comment]
Updated my Request. I came up with a draft and the FilterOnObservableFixture passes with my FilterOnObservable variant that is utilizing TransformOnObservable 👍

**Comment by RolandPheasant** [comment]
I'll be sure to look at this soon. I just need to wait until after Xmas as these operators require full focus to consider details from every angle. In the meantime have you been able to produce any unit tests?

**Comment by dwcullop** [comment]
I'm trying to understand how one would use this.  I would consider implementing it if I can understand its value.

Can you explain in terms of a ChangeSet what happens?
The input is `IObservable<IChangeSet<IObservable<TObject>>>`
The output is `IObservable<IChangeSet<TObject>>`.

I need to know what happens to the output for each possible change of the input.

Like for Add, it will subscribe to the added `IObservable<TObject>`, but then it emits a changeset out, so how does it map those TObjects back to a ChangeSet?  Is It "Add" for the first one and "Update" for the subsequent ones, until there's a Remove?  And then it unsubscribes and then emits a remove event for that one item?

Maybe a specific example of a problem you'd like to solve with this would be helpful.

**Comment by JakenVeina** [comment]
I would expect precisely what you describe, yes. Seems like the idea is to model a transform that changes over time, similar to how `.FilterOnObservable()` models a filter that changes over time. So, the first item from each stream is an add, each subsequent item is a replace, and completion is a remove.

I'll wager this functionality is now covered in some fashion by `.MergeManyChangeSets<>`

**Comment by dwcullop** [comment]
@KeilFelix `FilterOnObservable` for Cache Changesets has been added by #735.  I find the concept of `TransformOnObservable` intriguing, so I'm considering implementing it.

To align with the other `Transform` operators, the operator would need to take the observable changeset and a transform function, so the prototype would be something like:

```csharp
IObservable<IChangeSet<TDestination, TKey>> TransformByObservable<TObject, TKey, TDestination>(
    this IObservable<IChangeSet<TObject, TKey>> source,
    Func<TObject, IObservable<TDestination>> transformer);
```

The transform function would transform each item in the changeset to an observable... When that observable emits a value, that would be the value for the associated key in the resulting changeset and expressed as an Add event.  When it emits subsequent values, it would be expressed as an Update event.

An open question is whether `OnComplete` events from the sub-observables indicate the last value or that the value should be removed?  @JakenVeina indicated the latter, but I tend to think it should be the former.  To remove a value, it should be removed from the source.

When the source and all sub-observables have completed, the resulting changeset should complete.

As for errors, I tend to think an error should bring down the resulting observable because this could be mitigated by the transform function.

**Comment by dwcullop** [comment]
We could also do something like `TransformMany` where ALL of the values from the observable would be emitted in the changeset, and the key value for each would be determined by a supplied key-selector function.  There isn't a `TransformMany` overload that supports this, but it seems like that should be doable (and also for `TransformManyAsync`).  However, as @JakenVeina points out, this would be covered by `MergeManyChangeSets` if there were an operator to take a `IObservable<T>` and a key-selector and make it an observable changeset (of just add/update events).  I don't think that operator exists, but if it did, it could be combined with `MergeManyChangeSets` to create the `TransformManyOnObservable` behavior.

**Comment by dwcullop** [comment]
The OP also suggested (in #409) something like `GroupOnObservable` which I can only summarize would have a prototype such as:

```csharp
 IObservable<IGroupChangeSet<TObject, TKey, TGroupKey>> GroupOnObservable<TObject, TKey, TGroupKey>(
    this IObservable<IChangeSet<TObject, TKey>> source,
    Func<TObject, TKey, IObservable<TGroupKey>> groupOnObservable);
```

Which would group the values based on the last value returned from each sub-observable.  When a new value is fired, the corresponding value would move from one group to another.

I'm also interested in such an operator because, for another project, I need something like `GroupAsync` (because obtaining the value to group on is an async operation).  `GroupOnObservable` would cover that case nicely as I could just convert the Async operation to an IObservable that fires once.

**Comment by JakenVeina** [comment]
> An open question is whether OnComplete events from the sub-observables indicate the last value or that the value should be removed?

If the signature defines a transform as `Func<TIn, IObservable<TOut>>` I would definitely be on the side of "completion of a sub-stream just indicates that there will be no further changes to the transformation result, not that the item should be removed.

**Comment by RolandPheasant** [comment]
> I would definitely be on the side of "completion of a sub-stream just indicates that there will be no further changes to the transformation result, not that the item should be removed.

100% agree.

**Comment by KeilFelix** [comment]
I am really happy to see activity here.
As to the removal behavior: It should be consistent to the behavior in FilterOnObservable and also to other future OnObservable Operators like (Group). As far as I remember FilterOnObservable removes but I need to recheck this.

And I still prefer the removal behavior because
values from Completed Observables cannot be distinguished from the other still active Observables.
So the removal maybe the desired behavior in many use cases. The user can easily achieve the non removing behavior by Concat Observable.Never when he selects the Observable. But if it is implemented the other way it is not that easy to achieve the removing behavior.

**Comment by dwcullop** [comment]
> I am really happy to see activity here. As to the removal behavior: It should be consistent to the behavior in FilterOnObservable and also to other future OnObservable Operators like (Group). As far as I remember FilterOnObservable removes but I need to recheck this.

`FilterOnObservable` will use the last value from the observable to control whether or not it passes the filter (completed or not).  If the observable completes, it just means the filter/unfiltered status will no longer change for that item.

Considering this and the fact that both @JakenVeina and @RolandPheasant agree, I implemented it without the removing behavior.  When the child-observable completes, it just means no more updates for that key will be seen.  When all the child-observables have completed (and the source has completed) then the Transformed sequence will also fire `OnCompleted`.

To me, it seems inconsistent for a Transform operator to remove items from the stream unless they're removed from the source.

If you really need it, you can make a custom operator that uses a temporary Intermediate cache and emits a remove event when the transform-observable completes.  It isn't as straight-forward as just `.Concat(Observable.Never<T>())` but it is still doable.

**Comment by dwcullop** [comment]
@KeilFelix  If you really have a need for the "Remove on OnCompleted" behavior, open a new issue so it can be discussed.  I don't want to just add parameters that someone MIGHT use someday.  

If there is consensus that it is generally useful, we can add a parameter to the operator that will give the option of that behavior.

**Comment by RolandPheasant** [comment]
The remove items on complete was there for the dispose operator only and I don't think it's required elsewhere. I'll double check my assuming tomorrow.
