### ISSUE TITLE
[Bug]: BindingListAdaptor does not support Refresh/Evaluate for items

### ISSUE THREAD

**Issue by Metadorius** [reactivemarbles/DynamicData#676]
### Describe the bug 🐞

I noticed that when I call `Refresh` on an item in `SourceCache`, it doesn't propagate to my WinForms-based UI (it uses `BindingList`) it's bound to. Upon further examination of the problem I found that while `SourceCache` itself seems to be fine, the `BindingList` doesn't receive any notifications. It seems the culprit is the `BindingListAdaptor` which just doesn't have any sort of `Refresh` handling and just does nothing when `Refresh` comes, despite BindingList being able to handle such changes (see `ResetItem`; although this is just my assumption, I am still investigating): https://github.com/reactivemarbles/DynamicData/blob/ec02c3b84d6272b812c3ad5c21b2ee30ce8b41e7/src/DynamicData/Binding/BindingListAdaptor.cs#L112

### Step to reproduce

1. Create a `SourceCache` with some items.
2. Insert a `Do` with logging to see the changes emitted.
3. Bind to a `BindingList`.
4. Subscribe to the binding list's change event with another logging check.
5. Call `Refresh(item)` on SourceCache.

### Reproduction repository

https://github.com/Metadorius/DynamicData.BindingListRefreshRepro

### Expected behavior

Both SourceCache and BindingList should reflect the change.

### DynamicData Version

7.12.1

### Additional information ℹ️

Running on .NET Framework 4.8.

**Comment by Metadorius** [comment]
On another thought lemme isolate the issue, I'll be back with a reproduction repo.

**Comment by Metadorius** [comment]
This actually happens in a `SortedBindingListAdaptor` too. For some reason `Refresh` is unhandled properly.

Here's a repro repo: https://github.com/Metadorius/DynamicData.BindingListRefreshRepro

**Comment by Metadorius** [comment]
@RolandPheasant any thoughts on this? maybe I could assist with fixing that, I am just unsure on how should I proceed if I do, since `Refresh` seems to be a "reset all" type of notification? Maybe it would be better to emit `Update`?

**Comment by RolandPheasant** [comment]
Refresh is purely to instruction for an operator to check again.  For example when a filter is property based it may be that a property changes so if the filter is:

```cs
var filtered = mySource.Connect()
    .AutoRefresh(x => x.IsSelected) // monitor inline property changes
    .Filter(x => x.IsSelected)  // filter on that property and respond to refresh when the property changes
```
If IsSelected changes, the filter receives a Refresh for the changed record, the filtered result will change. In other words the refresh causes a change in the filter result and the refresh event get's promoted to and Add, or a Remove.

The same concept applies to many but not all operators.  In the case of a binding list, a refresh which represents an inline change the list itself cannot respond as a property change cannot result in any operation on the binding list itself. Therefore it is ignored.

What were you expecting, or is there some subtlety of winforms binding that I am missing?

**Comment by RolandPheasant** [comment]
Ah, I get it now. I did not know about reset item - it's been at least 12 years since I last used binding list!  The solution is:


```cs
      case ChangeReason.Refresh:
          {
              var index = list.IndexOf(update.Current);
              if (index != -1)
                  list.ResetItem(index);
              break;
          }
```
in the adaptor.  I'll have to apply the fix to the sorted adaptor too, which is a little tricier..

**Comment by RolandPheasant** [comment]
This should do it:  https://github.com/reactivemarbles/DynamicData/pull/678

I'll write some tests hopefully tomorrow.
