### ISSUE TITLE
[Feature]: Specify `ListFilterPolicy` when using a lambda

### ISSUE THREAD

**Issue by Nextra** [reactivemarbles/DynamicData#696]
### Describe the functionality desired 🐞

The `Filter` variant for `Func<T, bool>` (as opposed to `IObservable<Func<T, bool>>`) does not allow specifying a `ListFilterPolicy`.

### The steps the functionality will provide

1. Should compile:
```csharp
new SourceList<string>().Connect().Filter(s => s == "test", ListFilterPolicy.ClearAndReplace).Subscribe();
```

### Considerations

Passing the Lambda with `Observable.Return`

**Comment by RolandPheasant** [comment]
_ListFilterPolicy_ has never been applied to the lambda overload because it only has effect when the lambda changes.  A static lambda can never change so it makes no sense.

**Comment by Nextra** [comment]
Understood, was not aware of this detail. Thanks.
