### ISSUE TITLE
[Feature]: Please create a signed version, with strong name key.

### ISSUE THREAD

**Issue by t4m45** [reactivemarbles/DynamicData#705]
### Describe the functionality desired 🐞

Please create a signed version, with strong name key.
Our .net framework projects are signed with strong name key file and the app will not run if we install this nuget package, since it does not have a strong name.

The version could be on a different branch.. even I would do the signing but I can't because we don't have vs22 yet and I cannot build this project with vs19 since it requires .net 6 and 7.

`System.IO.FileLoadException: Could not load file or assembly 'DynamicData, Version=7.14.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044).`

Thanks!

### The steps the functionality will provide

The package shall be used in signed projects.

### Considerations

-

**Comment by glennawatson** [comment]
Strong naming is only useful in very limited scenarios hence why it was removed in older versions of .net

https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

Lot of people are confused it gives  extra security but it doesn't
