### ISSUE TITLE
Windows 11 - Smart App Control

### ISSUE THREAD

**Issue by emik-dev** [reactivemarbles/DynamicData#707]
### Describe the bug 🐞

Windows 11 is introducing Smart App Control. One of the security checks for apps is ensuring that the app and its binaries are signed. Because DynamicData does not sign its binaries, software using it will be blocked from running when Smart App Control is enabled.

Please sign DLLs produced for DynamicData.

https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003

### Step to reproduce

.

### Reproduction repository

https://github.com/reactivemarbles/DynamicData

### Expected behavior

.

**Comment by glennawatson** [comment]
Different kind of signing. They are talking about code sign certificates. 

https://www.digicert.com/signing/code-signing-certificates#:~:text=Code%20Signing%20Certificates%20are%20used,compromised%20by%20a%20third%20party.
