### ISSUE TITLE
[Bug]: `AddRange` `ChangeSet` has unexpected `Index` of -1

### ISSUE THREAD

**Issue by PhilipCavanagh** [reactivemarbles/DynamicData#723]
### Describe the bug 🐞

While writing a new operator for our internal use, I unexpectedly encountered an `AddRange` `ChangeSet` with an `Index` of -1. I traced it back to [line 88 in SourceList.Connect()](https://github.com/reactivemarbles/DynamicData/blob/main/src/DynamicData/List/SourceList.cs#L88), which leaves the index at its default of -1.

One of two things is true:
- It's legal for an `AddRange` `ChangeSet` to have an index of -1, and it presumably means something like "this is the initial state of the collection". If that's the case, it ought to be documented somewhere, and I've found nothing.
- This is a bug and 0 should be passed as the index.

### Steps to reproduce

        var source = new SourceList<string>();
        source.Add("A");
        var changeSets = new List<IChangeSet<string>>();
        source.Connect().Subscribe(changeSets.Add).Dispose();
        Trace.Assert(changeSets[0].First().Type == ChangeType.Range);

        // This assertion fails
        Trace.Assert(changeSets[0].First().Range.Index >= 0);

### Expected behavior

I was expecting Index to equal zero for an `AddRange` that initialises the collection.

### DynamicData Version

7.13.1

**Comment by JakenVeina** [comment]
There's a couple references to the index being -1 that I can find.

https://github.com/reactivemarbles/DynamicData/blob/0292f191960f739653e9a01bcbf19c38bcd99d5a/src/DynamicData/List/ListEx.cs#L73

https://github.com/reactivemarbles/DynamicData/blob/0292f191960f739653e9a01bcbf19c38bcd99d5a/src/DynamicData/List/Internal/Transformer.cs#L78

I don't see any particular reason, other than it being a "shorthand" for saying "append to the end of the list". Definitely could use a bit of documentation on `RangeChange<T>.Index` if that's the case.
