### ISSUE TITLE
[Feature]: Add FilterNodes extension method when using TransformToTree /w Children-aware filtering

### ISSUE THREAD

**Issue by lltwist** [reactivemarbles/DynamicData#737]
### Describe the functionality desired 🐞

The question was already raised in [[Question] Child node filtering when using TransformToTree  ](https://github.com/reactivemarbles/DynamicData/issues/311) , but closed.

Right now .Filter is filtering only root nodes of cache. There is no access to children to do it manually cause Children are exposed only as IObservableCache, method Update is also internal. Also there is no available methods to ovveride FilterStatic to implement custom Node aware logic.

It might be great to filter tree by keys, with option to leave whole branch (ancestors) up to filtering key.

Also great to have Ancestors auro-prop in Node.

Thanks

### Considerations

Custom ovveride

**Comment by JakenVeina** [comment]
Shouldn't you be able to accomplish this by just applying `.Filter()` before `.TransformToTree()`?

**Comment by RolandPheasant** [comment]
Closing, @JakenVeina is correct
