### ISSUE TITLE
[Performance]:  Don't use Scheduler.Default as the default scheduler

### ISSUE THREAD

**Issue by dwcullop** [reactivemarbles/DynamicData#854]
### Performance Improvement

Define some static read-only value that represents the `IScheduler` instance to use when one isn't provided.  We can then determine the best way to that value should be initialized.

![image](https://github.com/reactivemarbles/DynamicData/assets/11876551/4d74bca0-4608-4c97-bdcf-de005dca469f)

**Comment by JakenVeina** [comment]
So, we're talking about something like a `DynamicData.DefaultScheduler` property somewhere that is actually `public`, for consumers to configure however they like. And we can default it to `ThreadPoolScheduler` or whatever. That sounds reasonable to me.

One thing we'd want to consider is where we're pulling the field value dynamically, versus pulling it and caching it forever, say, within an operator. Practically speaking, I think the intent of this static field is that consumers would set it once, upon startup, but we do want to make sure that if the user changes it, we haven't already pulled and captured the value anywhere, and thus wouldn't recognize the change. Maybe we could do something fancy that would actually *detect* if you're trying to change the field after it's already started being used, and throw an exception.

**Comment by dwcullop** [comment]
I wasn't thinking it would be exposed publicly.  Just something internal that we can have some logic to set to the best value and have all the internal operators use that instead of some other way of getting the default.
