### ISSUE TITLE
[Feature]: ToObservableChangeSet option to emit initial ChangeSet even if empty

### ISSUE THREAD

**Issue by geferon** [reactivemarbles/DynamicData#903]
### Describe the functionality desired 🐞

Currently the ToObservableChangeSet will only emit an initial value if there are any values in the collection, if the collection is empty nothing will emit until it is somehow modified.

Usage:
```cs
var collection = new ObservableCollection();
collection.ToObservableChangeSet()
	.ToCollection()
	.Subscribe(values => Console.WriteLine(values)); // This doesn't get called at all
```

Solution(?):
Add a new parameter such as `bool emitEmpty = false` which will evaluate to the following:
```cs
// This is currently code in ObservableCollectionEx.cs https://github.com/reactivemarbles/DynamicData/blob/76fd915924fab0e6756038f50a4fff4464a4ed00/src/DynamicData/Binding/ObservableCollectionEx.cs#L122-L125
if (data.Count > 0)
{
    observer.OnNext(data.CaptureChanges());
}
// NEW CHECK
else if (emitEmpty)
{
	observer.OnNext(ChangeSet<T>.Empty);
}
```
Or you at least could document this behaviour in the method calls as I had to look into the source code to see why it wasn't emitting any initial values.;

Currently the way I'm handling this locally is:
```cs
var collection = new ObservableCollection();
var observable = collection.ToObservableChangeSet();

if (!collection.Any())
	observable = observable.Merge(Observable.Return(ChangeSet<T>.Empty));

observable
	.ToCollection()
	.Subscribe(values => Console.WriteLine(values)); // This now gets called at least once even if the collection is empty
```

### The steps the functionality will provide

Provided in functionality desired

### Considerations

This is a minor issue that can be solved by doing 1 if and merging locally, this feature would be out of convenience and also to make it clearer, as ToObservableChangeSet emits an initial value if there are values in the collection provided but doesn't if it's empty, I think this is counter-intuitive if not told about in the documentation at least?

**Comment by JakenVeina** [comment]
Yeah, this seems like a no-brainer enhancement. Hell, me personally, I wouldn't necessarily be against just making this the default behavior, but I'd be interested in other opinions.

I agree with your reckoning as well, after plumbing the parameter down into the operator logic, it's the one-liner change you describe, [here](https://github.com/reactivemarbles/DynamicData/blob/76fd915924fab0e6756038f50a4fff4464a4ed00/src/DynamicData/Binding/ObservableCollectionEx.cs#L124). 

You've got first dibs on a PR, if you want.

In the meantime, your workaround is reasonable. If you wanted to be a little more, uhh.... functional about it, you could do...

```cs
var collection = new ObservableCollection();
Observable.Create(observer =>
    {
        if (collection.Count is 0)
            observer.OnNext(ChangeSet<T>.Empty);

        return collection.ToObservableChangeSet().SubscribeSafe(observer);
    })
    .ToCollection()
    .Subscribe(values => Console.WriteLine(values)); // This doesn't get called at all
```

**Comment by geferon** [comment]
Should I add a test for it? I've noticed changing that breaks multiple tests but only because they expect the message count to be 1 and it's 2 as an Empty is emitted initially.

**Comment by JakenVeina** [comment]
Yeah, in general, add a test to cover additional functionality. And changing the expected message count in existing tests is entirely fine, so long as it matches the desired behavior.

Hang tight, though, for now, until we get some feedback on what the "desired behavior" is, I.E. whether we want to add the parameter, or just change the behavior itself.

**Comment by RolandPheasant** [comment]
It's only suppresses the initial state for historic reasons, and it's good to change it. 

We can release it as a major version change because it could potentially break some code in the wild.

**Comment by JakenVeina** [comment]
Sounds good to me.

This is basically the behavior we talked about for DDNext, all operators should guarantee a first-changeset upon subscribe, and then filter empties afterwards.

We have some other major-version-bumping stuff, so we can put this in with whenever that ends up happening.

**Comment by JakenVeina** [comment]
@geferon If you still want dibs on a PR, go for it, we'll be ready to do a release when it's done.
