### ISSUE TITLE
[Bug]: SortAndBind() method will never create a NotifyCollectionChangedAction.Move in the resulting (observable) list when sorting order changes

### ISSUE THREAD

**Issue by kristian-pettersen** [reactivemarbles/DynamicData#934]
### Describe the bug 🐞

When using the new SortAndBind() method and binding into an observable list, it will always produce Remove and Add operations in the bound list when the sorting order changes and an item needs to be moved. When the bound list is then used as a source for a CollectionView which is bound into a UI Selector, like a DataGrid, this might cause problems with the Selector loosing its selection if the selected item is moved (removed/added again) as a result of dynamic sorting. It does not always happen - I am guessing there might be some race-condition or maybe varying item template complexity might affect this.

There might be other side-effects to this as well, I guess. I would suppose that the Move operation yields better performance than a combination of Remove/Add - for lists that support Move.

Using the legacy Sort().Bind() will produce Move events in the bound observable list.

### Step to reproduce

```cs
ReadOnlyObservableCollection<MyItem> sortedCollection;
_sourceObservableCollection.ToObservableChangeSet(i => i.Key)
    ObserveOn(schedulerProvider.ApplicationDispatcher)
    SortAndBind(out sortedCollection, _observableItemComparer)
    Subscribe();
    
sortedCollection.ObserveCollectionChanges()
    .Subscribe(ep =>
    {
        if (ep.EventArgs.Action == NotifyCollectionChangedAction.Move)
        {
            // Winning! (will never happen ...)
        }
    });
```

### Reproduction repository

https://github.com/kristian-pettersen/DynamicData

### Expected behavior

I think the SortAndBind() method should use Move instead of Remove/Add when possible.
I have included a commit with my suggestion in my fork of the repo.

**Suggested solution:**

in `DynamicData/Cache/Internal/SortExtensions.cs`:
_Add extension method:_
```cs
    public static void Move<TItem>(this IList<TItem> list, int original, int destination, TItem item)
    {
        // If the list supports the Move method, use it instead of removing and inserting.
        if (list is IExtendedList<TItem> extendedList)
        {
            extendedList.Move(original, destination);
        }
        else if (list is ObservableCollection<TItem> observableList)
        {
            observableList.Move(original, destination);
        }
        else
        {
            list.RemoveAt(original);
            list.Insert(destination, item);
        }
    }
```

in `DynamicData/Binding/SortAndBind.cs`:
_Lines 195 - 196 replaced by:_
```cs
                                target.Move(currentIndex, updatedIndex, item);
```

This is my attempt to make this work - it might be possible for more elegant and maybe more complete solutions, but at least this works and proves my point.

### DynamicData Version

9.0.4

### Additional information ℹ️

I did not produce any unit tests, as I did not understand the test structure/usage in the solution. I guess you are able to create a much more precise test than me for this case. I think my 1 commit in the repo, containing the suggested solution is quite simple and speaks for itself.

**Comment by JakenVeina** [comment]
I'm definitely gonna have to defer to @RolandPheasant, because looking at this operator, it's missing a lot of things I assumed it would have, as a replacement for `.Bind()`. For example, it has no adapter layer, which is where the code changes you suggest would belong. I dunno what missing pieces were intentionally left out, to streamline the operator, or simply deemed not necessary for a minimum viable implementation, and intended to be added later.

Either way, I agree, there's no reason this operator shouldn't be performing `Move` operations, for targets that support them. I'm just not sure what the proper implementation is.

In the meantime, feel free to continue using `.Sort()`. Deprecated or not, it's not going away until `.SortAndBind()` can fully serve as a replacement.

**Comment by RolandPheasant** [comment]
> In the meantime, feel free to continue using .Sort(). Deprecated or not, it's not going away until .SortAndBind() can fully serve as a replacement.  

I agree this, and you can also disable the warning at the project or solution level.  Doing so may be a good interim solution until any flaws in BindAndSort  are ironed out.

Regarding the move extension, excellent spot and analysis.  This idea looks good to me.  Would you be happy to raise a PR?

**Comment by kristian-pettersen** [comment]
> Regarding the move extension, excellent spot and analysis. This idea looks good to me. Would you be happy to raise a PR?

Of course I will. Thank you.
