### ISSUE TITLE
[Bug]: Operator Switch does not propagate errors to the downstream

### ISSUE THREAD

**Issue by dmalukov** [reactivemarbles/DynamicData#966]
### Describe the bug 🐞

I’ve described the problem in the test case below.

In summary, the Switch operator disrupts error propagation and suppresses exceptions.
In my case, these exceptions are not caught by RxApp.DefaultExceptionHandler either, causing the app to crash.

The operator's documentation does not mention this behavior, so I consider it a bug.

### Step to reproduce

```c#
    [Fact]
    public void PropagatesErrors()
    {
        bool exceptionCaught = false;

        List<List<int>> listOfLists = [[0, 1, 2]];

        listOfLists.ToObservable()
            .ToObservableChangeSet(int (int value) => value)
            .Select(set =>
            {
                throw new Exception();              // Something bad happened here
                return Observable.Return(set);
            })
            .Do(_ => { }, e => { })                 // here the error handler is called
            .Switch()                               // here the exception is swallowed
            .Catch((Exception e) =>                 // this code will never be executed
            {
                exceptionCaught = true;
                return Observable.Empty<IChangeSet<int, int>>();
            })
            .Subscribe();

        Assert.True(exceptionCaught);
    }
   ```

### Reproduction repository

https://github.com/dmalukov/DynamicDataSwitchRepro

### Expected behavior

The error should be propagated and not swallowed.

**Comment by JakenVeina** [comment]
Proper error propagation is something that's come up a handful of times, since I joined the project. We've had maintainer discussions about what the proper behavior should be, across the board, and yeah, errors should almost always be propagated downstream. The `.Switch()` operator is old enough, it's probably just wrong. I'll have a look to see if there's an easy fix.

**Comment by JakenVeina** [comment]
I think that does work, yeah. Honestly, a hair cleaner than my solution, I think.

I will point out that there's a native operator that's equivalent to your use of `.Where(_ => false)`: `.IgnoreElements()`.
